create extension if not exists pgcrypto;

create or replace function public.northlight_pilot_allowed()
returns boolean
language sql
stable
as $$
  select coalesce(
    encode(digest(coalesce(current_setting('request.headers', true)::jsonb ->> 'x-northlight-demo-key',''), 'sha256'), 'hex') = '8727b61597b7ec467fed2a3cd2dd5aacebf477976a02850e8ba44138e347db70',
    false
  )
$$;

create table if not exists public.tenants (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, brand_name text not null, timezone text not null default 'Australia/Melbourne', settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.roles (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, code text not null, name text not null, permissions jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), unique (tenant_id, code));
create table if not exists public.users (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, role_code text not null, name text not null, email text not null, phone text, password_hash text not null, avatar_url text, active boolean not null default true, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique (tenant_id, email));
create table if not exists public.services (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, code text not null, name text not null, category text not null default 'media', duration_min integer not null default 60, buffer_before_min integer not null default 15, buffer_after_min integer not null default 15, active boolean not null default true, sort_order integer not null default 0, metadata jsonb not null default '{}'::jsonb, unique (tenant_id, code));
create table if not exists public.packages (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, name text not null, service_codes text[] not null default '{}', active boolean not null default true, metadata jsonb not null default '{}'::jsonb);
create table if not exists public.provider_profiles (user_id uuid primary key references public.users(id) on delete cascade, tenant_id uuid not null references public.tenants(id) on delete cascade, areas text[] not null default '{}', service_codes text[] not null default '{}', working_hours jsonb not null default '{}'::jsonb, days_off jsonb not null default '[]'::jsonb, special_days jsonb not null default '[]'::jsonb, home_base text, current_load integer not null default 0, priority integer not null default 100, certifications jsonb not null default '[]'::jsonb, preferences jsonb not null default '{}'::jsonb);
create table if not exists public.editor_profiles (user_id uuid primary key references public.users(id) on delete cascade, tenant_id uuid not null references public.tenants(id) on delete cascade, skills text[] not null default '{}', current_load integer not null default 0, preferences jsonb not null default '{}'::jsonb);
create table if not exists public.resources (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, code text not null, name text not null, quantity integer not null default 1, service_codes text[] not null default '{}', areas text[] not null default '{}', active boolean not null default true, metadata jsonb not null default '{}'::jsonb, unique (tenant_id, code));
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, task_no text not null, property_name text not null, address text not null, suburb text not null, area text not null, priority text not null default 'standard' check (priority in ('standard','priority','rush')), status text not null default 'assigned', agent_user_id uuid references public.users(id), photographer_user_id uuid references public.users(id), editor_user_id uuid references public.users(id), scheduled_start timestamptz, scheduled_end timestamptz, service_codes text[] not null default '{}', notes text, dropbox_path text, calendar_event_id text, revision_count integer not null default 0, next_action text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (tenant_id, task_no));
create table if not exists public.task_events (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, task_id uuid not null references public.tasks(id) on delete cascade, type text not null, actor_user_id uuid references public.users(id), detail jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.revisions (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, task_id uuid not null references public.tasks(id) on delete cascade, number integer not null, requested_by_user_id uuid references public.users(id), note text not null, status text not null default 'requested', created_at timestamptz not null default now(), resubmitted_at timestamptz, approved_at timestamptz, unique (task_id, number));
create table if not exists public.notification_events (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, task_id uuid references public.tasks(id) on delete cascade, channel text not null, recipient text not null, template text, status text not null default 'queued', provider_id text, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.integration_state (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, provider text not null, status text not null default 'not_connected', account_label text, last_verified_at timestamptz, metadata jsonb not null default '{}'::jsonb, unique (tenant_id, provider));

create index if not exists tasks_tenant_status_idx on public.tasks(tenant_id, status);
create index if not exists tasks_schedule_idx on public.tasks(tenant_id, scheduled_start);
create index if not exists events_task_idx on public.task_events(task_id, created_at desc);
create index if not exists notifications_task_idx on public.notification_events(task_id, created_at desc);

alter table public.tenants enable row level security; alter table public.roles enable row level security; alter table public.users enable row level security; alter table public.services enable row level security; alter table public.packages enable row level security; alter table public.provider_profiles enable row level security; alter table public.editor_profiles enable row level security; alter table public.resources enable row level security; alter table public.tasks enable row level security; alter table public.task_events enable row level security; alter table public.revisions enable row level security; alter table public.notification_events enable row level security; alter table public.integration_state enable row level security;

do $$ declare t text; begin foreach t in array array['tenants','roles','users','services','packages','provider_profiles','editor_profiles','resources','tasks','task_events','revisions','notification_events','integration_state'] loop execute format('drop policy if exists northlight_pilot_access on public.%I', t); execute format('create policy northlight_pilot_access on public.%I for all to anon, authenticated using (public.northlight_pilot_allowed()) with check (public.northlight_pilot_allowed())', t); end loop; end $$;
