import test from'node:test';
import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import{evaluateBooking,zonedLocalToUtc}from'../functions/_lib/scheduling.js';

const realFetch=globalThis.fetch;
const base={user:{id:'11111111-1111-4111-8111-111111111111',name:'Priya Nair',email:'priya@example.com',role_code:'photographer',active:true},profile:{user_id:'11111111-1111-4111-8111-111111111111',areas:['Inner East'],service_codes:['photos','drone'],working_hours:{mon:['08:00','18:00'],tue:['08:00','18:00'],wed:['08:00','18:00'],thu:['08:00','18:00'],fri:['08:00','18:00']},days_off:[],special_days:[],timezone:'Australia/Melbourne',calendar_id:'primary'},services:[{code:'photos',duration_min:60,buffer_before_min:10,buffer_after_min:15,active:true},{code:'drone',duration_min:30,buffer_before_min:5,buffer_after_min:20,active:true}],tasks:[],integration:{tenant_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',user_id:'11111111-1111-4111-8111-111111111111',provider:'google',status:'connected',metadata:{access_token:'token',access_expires_at:4102444800000}},googleBusy:[]};
const env={SUPABASE_URL:'https://db.test',SUPABASE_PUBLISHABLE_KEY:'pk',NORTHLIGHT_DEMO_KEY:'pilot',TOKEN_ENCRYPTION_KEY:'not-used'};
function install(overrides={}){const data={...base,...overrides};globalThis.fetch=async(url,opt={})=>{const u=new URL(String(url));if(u.origin==='https://db.test'){const table=u.pathname.split('/').pop();let out=[];if(table==='users')out=data.user?[data.user]:[];else if(table==='provider_profiles')out=data.profile?[data.profile]:[];else if(table==='services')out=data.services||[];else if(table==='tasks')out=data.tasks||[];else if(table==='tenants')out=[{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',slug:'realcapture',settings:{}}];else if(table==='user_integrations')out=data.integration?[data.integration]:[];return new Response(JSON.stringify(out),{status:200,headers:{'content-type':'application/json'}})}if(u.origin==='https://www.googleapis.com'&&u.pathname.endsWith('/freeBusy'))return new Response(JSON.stringify({calendars:{primary:{busy:data.googleBusy||[]}}}),{status:200,headers:{'content-type':'application/json'}});throw new Error(`unexpected fetch ${url}`)};return data}
async function evaluate(overrides={},input={}){install(overrides);return evaluateBooking(env,{photographerId:base.user.id,area:'Inner East',serviceCodes:['photos','drone'],startLocal:'2026-08-24T09:00',requireActiveServices:true,...input})}

test('Melbourne local time is interpreted deterministically',()=>{assert.equal(zonedLocalToUtc('2026-08-24T09:00','Australia/Melbourne').toISOString(),'2026-08-23T23:00:00.000Z')});
test('selected services determine duration and protected buffers',async()=>{const d=await evaluate();assert.equal(d.available,true);assert.equal(d.code,'AVAILABLE');assert.equal(d.durationMinutes,90);assert.equal(d.bufferBeforeMinutes,10);assert.equal(d.bufferAfterMinutes,20);assert.equal(d.start.toISOString(),'2026-08-23T23:00:00.000Z');assert.equal(d.end.toISOString(),'2026-08-24T00:30:00.000Z')});
test('a Photographer without connected Calendar is never offered as bookable',async()=>{const d=await evaluate({integration:null});assert.equal(d.available,false);assert.equal(d.connected,false);assert.equal(d.code,'GOOGLE_REQUIRED');assert.match(d.reason,/must connect Google Calendar/)});
test('inactive Photographer is never eligible',async()=>{const d=await evaluate({user:{...base.user,active:false}});assert.equal(d.available,false);assert.equal(d.code,'PHOTOGRAPHER_NOT_ELIGIBLE')});
test('area and every service are server eligibility requirements',async()=>{const area=await evaluate({}, {area:'Bayside'});assert.equal(area.code,'AREA_NOT_COVERED');const service=await evaluate({profile:{...base.profile,service_codes:['photos']}});assert.equal(service.code,'SERVICE_NOT_CONFIGURED');assert.deepEqual(service.missingServices,['drone'])});
test('working hours and special unavailability block the slot',async()=>{const early=await evaluate({}, {startLocal:'2026-08-24T06:30'});assert.equal(early.available,false);assert.equal(early.code,'WORKING_HOURS');const dayOff=await evaluate({profile:{...base.profile,days_off:['2026-08-24']}});assert.equal(dayOff.code,'DAY_OFF')});
test('active Northlight booking collision blocks protected window',async()=>{const d=await evaluate({tasks:[{id:'22222222-2222-4222-8222-222222222222',task_no:'NL-EXIST',property_name:'Existing',scheduled_start:'2026-08-23T22:55:00.000Z',scheduled_end:'2026-08-24T00:40:00.000Z',status:'confirmed'}]});assert.equal(d.available,false);assert.equal(d.code,'NORTHLIGHT_CONFLICT')});
test('connected Google Calendar busy period blocks the exact same slot',async()=>{const d=await evaluate({integration:{tenant_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',user_id:base.user.id,provider:'google',status:'connected',metadata:{access_token:'token',access_expires_at:Date.now()+3600000}},googleBusy:[{start:'2026-08-23T23:30:00Z',end:'2026-08-24T00:00:00Z'}]});assert.equal(d.available,false);assert.equal(d.connected,true);assert.equal(d.code,'GOOGLE_BUSY')});
test('product and role source contracts stay intact',async()=>{const tasks=await readFile(new URL('../functions/api/tasks.js',import.meta.url),'utf8'),schedule=await readFile(new URL('../functions/api/tasks/[id]/schedule.js',import.meta.url),'utf8'),app=await readFile(new URL('../assets/app-v2.js',import.meta.url),'utf8');assert.match(tasks,/priority:'standard'/);assert.match(tasks,/requestedPriority.*standard|priority.*standard/i);assert.match(app,/Standard booking\./);assert.doesNotMatch(app,/data-priority|id=["']wPriority|Priority booking|Rush booking|Urgent booking/i);assert.match(schedule,/function canCancel\(t,s\)\{return\['admin','owner'\]\.includes\(s\.role\)\|\|\(s\.role==='agent'/);assert.match(schedule,/RESCHEDULABLE=new Set\(\['assigned','confirmed','reschedule_requested'\]\)/)});

test.after(()=>{globalThis.fetch=realFetch});
