import test from'node:test';
import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import{allowedStage,validateFilename,validateUploadRequest,LARGE_UPLOAD_THRESHOLD,UPLOAD_CHUNK_SIZE}from'../functions/_lib/media-upload.js';
import{error,requireSession}from'../functions/_lib/core.js';

const task={id:'task-1',agent_user_id:'agent-1',photographer_user_id:'photo-1',editor_user_id:'editor-1',archived_at:null,deleted_at:null,dropbox_path:'/Northlight/NL-1 - 24 Albany Road',service_codes:['photos','drone']};
const admin={userId:'admin-1',role:'admin'},owner={userId:'owner-1',role:'owner'},agent={userId:'agent-1',role:'agent'},photographer={userId:'photo-1',role:'photographer'},editor={userId:'editor-1',role:'editor'},stranger={userId:'agent-2',role:'agent'};

test('media upload stage permissions preserve the Northlight role contract',()=>{for(const stage of['01_RAW','02_EDITED','03_FINAL','04_REFERENCE']){assert.equal(allowedStage(task,admin,stage),true);assert.equal(allowedStage(task,owner,stage),true)}assert.equal(allowedStage(task,agent,'04_REFERENCE'),true);assert.equal(allowedStage(task,agent,'01_RAW'),false);assert.equal(allowedStage(task,agent,'02_EDITED'),false);assert.equal(allowedStage(task,agent,'03_FINAL'),false);assert.equal(allowedStage(task,photographer,'01_RAW'),true);assert.equal(allowedStage(task,photographer,'04_REFERENCE'),true);assert.equal(allowedStage(task,photographer,'02_EDITED'),false);assert.equal(allowedStage(task,editor,'02_EDITED'),true);assert.equal(allowedStage(task,editor,'03_FINAL'),true);assert.equal(allowedStage(task,editor,'04_REFERENCE'),true);assert.equal(allowedStage(task,editor,'01_RAW'),false)});

test('property-media filename policy allows creative formats but blocks executable web content',()=>{for(const name of['living-room.CR3','drone.DNG','walkthrough.MOV','master.BRAW','floorplan.PDF','retouch.PSD','reference.ZIP'])assert.equal(validateFilename(name).ok,true,name);for(const name of['payload.html','script.js','installer.exe','shell.ps1','no-extension'])assert.equal(validateFilename(name).ok,false,name)});

test('upload validation enforces participant, stage, service, archive and size boundaries',()=>{assert.equal(validateUploadRequest(task,agent,{stage:'04_REFERENCE',filename:'brief.pdf',sizeBytes:1234}).ok,true);assert.equal(validateUploadRequest(task,stranger,{stage:'04_REFERENCE',filename:'brief.pdf',sizeBytes:1234}).status,404);assert.equal(validateUploadRequest(task,photographer,{stage:'02_EDITED',serviceCode:'photos',filename:'edit.jpg',sizeBytes:1234}).status,403);assert.equal(validateUploadRequest(task,photographer,{stage:'01_RAW',serviceCode:'video',filename:'clip.mov',sizeBytes:1234}).status,400);assert.equal(validateUploadRequest({...task,archived_at:new Date().toISOString()},admin,{stage:'01_RAW',serviceCode:'photos',filename:'raw.cr3',sizeBytes:1234}).status,409);assert.equal(validateUploadRequest(task,photographer,{stage:'01_RAW',serviceCode:'photos',filename:'raw.cr3',sizeBytes:0}).status,400);assert.equal(validateUploadRequest(task,photographer,{stage:'01_RAW',serviceCode:'photos',filename:'raw.cr3',sizeBytes:101*1024*1024*1024}).status,413)});

test('large-file thresholds are explicit and safe for Cloudflare subrequests',()=>{assert.equal(LARGE_UPLOAD_THRESHOLD,150*1024*1024);assert.equal(UPLOAD_CHUNK_SIZE,16*1024*1024);assert.ok(UPLOAD_CHUNK_SIZE<LARGE_UPLOAD_THRESHOLD)});

test('revision request is one server-side atomic command',async()=>{const status=await readFile(new URL('../functions/api/tasks/[id]/status.js',import.meta.url),'utf8'),ux=await readFile(new URL('../assets/ux-runtime.js',import.meta.url),'utf8'),migration=await readFile(new URL('../supabase/migrations/20260819113000_northlight_p1_workflow_media.sql',import.meta.url),'utf8');assert.match(status,/instructions=String\(b\.instructions\|\|''\)\.trim\(\)/);assert.match(status,/rpc\/northlight_request_revision/);assert.match(ux,/action:'request_revision',instructions:note/);assert.doesNotMatch(ux,/send\('\/api\/comments'.*Revision request/s);assert.match(migration,/create or replace function public\.northlight_request_revision/);assert.match(migration,/for update;/);assert.match(migration,/insert into public\.revisions/);assert.match(migration,/insert into public\.task_comments/);assert.match(migration,/update public\.tasks/);assert.match(migration,/insert into public\.task_events/)});

test('resumable upload path keeps provider credentials server-side and canonical indexing single',async()=>{const media=await readFile(new URL('../functions/_lib/media-upload.js',import.meta.url),'utf8'),start=await readFile(new URL('../functions/api/files/upload-session/start.js',import.meta.url),'utf8'),chunk=await readFile(new URL('../functions/api/files/upload-session/[id]/chunk.js',import.meta.url),'utf8'),finish=await readFile(new URL('../functions/api/files/upload-session/[id]/finish.js',import.meta.url),'utf8'),runtime=await readFile(new URL('../assets/certification-runtime.js',import.meta.url),'utf8');assert.match(media,/accessToken\(env,'dropbox'\)/);assert.doesNotMatch(start,/access_token|refresh_token/i);assert.doesNotMatch(chunk,/access_token|refresh_token/i);assert.doesNotMatch(finish,/access_token|refresh_token/i);assert.match(chunk,/confirmedOffset/);assert.match(finish,/markUploadSessionFinished/);assert.doesNotMatch(finish,/task_files|logEvent/);assert.match(runtime,/completedLargePaths/);assert.match(runtime,/\/api\/files\/complete-upload/)});

test('all assigned task participants can advance already-queued recovery without admin privilege',async()=>{const recovery=await readFile(new URL('../functions/api/handoffs/recover.js',import.meta.url),'utf8');assert.match(recovery,/s\.role==='photographer'/);assert.match(recovery,/s\.role==='editor'/);assert.match(recovery,/s\.role==='agent'/);assert.match(recovery,/recoverOneTaskHandoff/)});

test('public errors never echo raw exception strings but preserve structured business detail',async()=>{const hidden=await error(500,'Could not load task.','database_500:{"secret":"should-not-leak"}').json();assert.deepEqual(hidden,{error:'Could not load task.'});const structured=await error(422,'Photographer is not eligible.',{missingServices:['drone']}).json();assert.deepEqual(structured,{error:'Photographer is not eligible.',detail:{missingServices:['drone']}})});

test('session-protected cross-origin mutations are rejected before authentication or database access',async()=>{const req=new Request('https://northlight.example/api/tasks',{method:'POST',headers:{origin:'https://evil.example','sec-fetch-site':'cross-site','content-type':'application/json'},body:'{}'}),result=await requireSession(req,{});assert.equal(result.error.status,403);assert.deepEqual(await result.error.json(),{error:'Request origin is not allowed.'});const unauth=await requireSession(new Request('https://northlight.example/api/tasks'),{SESSION_SECRET:'unused'});assert.equal(unauth.error.status,401)});
