import test from'node:test';
import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import{allowedStage,validateFilename,validateUploadRequest,reviewPublishLocked,alternateUploadPath,LARGE_UPLOAD_THRESHOLD,UPLOAD_CHUNK_SIZE}from'../functions/_lib/media-upload.js';
import{error,requireSession}from'../functions/_lib/core.js';

const task={id:'task-1',status:'assigned',agent_user_id:'agent-1',photographer_user_id:'photo-1',editor_user_id:'editor-1',archived_at:null,deleted_at:null,dropbox_path:'/Northlight/NL-1 - 24 Albany Road',service_codes:['photos','drone']};
const admin={userId:'admin-1',role:'admin'},owner={userId:'owner-1',role:'owner'},agent={userId:'agent-1',role:'agent'},photographer={userId:'photo-1',role:'photographer'},editor={userId:'editor-1',role:'editor'},stranger={userId:'agent-2',role:'agent'};

test('media upload stage permissions preserve the Northlight role contract',()=>{for(const stage of['01_RAW','02_EDITED','03_FINAL','04_REFERENCE']){assert.equal(allowedStage(task,admin,stage),true);assert.equal(allowedStage(task,owner,stage),true)}assert.equal(allowedStage(task,agent,'04_REFERENCE'),true);assert.equal(allowedStage(task,agent,'01_RAW'),false);assert.equal(allowedStage(task,agent,'02_EDITED'),false);assert.equal(allowedStage(task,agent,'03_FINAL'),false);assert.equal(allowedStage(task,photographer,'01_RAW'),true);assert.equal(allowedStage(task,photographer,'04_REFERENCE'),true);assert.equal(allowedStage(task,photographer,'02_EDITED'),false);assert.equal(allowedStage(task,editor,'02_EDITED'),true);assert.equal(allowedStage(task,editor,'03_FINAL'),true);assert.equal(allowedStage(task,editor,'04_REFERENCE'),true);assert.equal(allowedStage(task,editor,'01_RAW'),false)});

test('property-media filename policy allows creative formats but blocks executable web content',()=>{for(const name of['living-room.CR3','drone.DNG','walkthrough.MOV','master.BRAW','floorplan.PDF','retouch.PSD','reference.ZIP'])assert.equal(validateFilename(name).ok,true,name);for(const name of['payload.html','script.js','installer.exe','shell.ps1','no-extension'])assert.equal(validateFilename(name).ok,false,name)});

test('upload validation enforces participant, stage, service, lifecycle, review lock and size boundaries',()=>{assert.equal(validateUploadRequest(task,agent,{stage:'04_REFERENCE',filename:'brief.pdf',sizeBytes:1234}).ok,true);assert.equal(validateUploadRequest(task,stranger,{stage:'04_REFERENCE',filename:'brief.pdf',sizeBytes:1234}).status,404);assert.equal(validateUploadRequest(task,photographer,{stage:'02_EDITED',serviceCode:'photos',filename:'edit.jpg',sizeBytes:1234}).status,403);assert.equal(validateUploadRequest(task,photographer,{stage:'01_RAW',serviceCode:'video',filename:'clip.mov',sizeBytes:1234}).status,400);assert.equal(validateUploadRequest({...task,archived_at:new Date().toISOString()},admin,{stage:'01_RAW',serviceCode:'photos',filename:'raw.cr3',sizeBytes:1234}).status,409);assert.equal(validateUploadRequest({...task,status:'cancelled'},admin,{stage:'01_RAW',serviceCode:'photos',filename:'raw.cr3',sizeBytes:1234}).status,409);assert.equal(validateUploadRequest({...task,status:'delivered'},owner,{stage:'03_FINAL',serviceCode:'photos',filename:'final.jpg',sizeBytes:1234}).status,409);const locked={...task,metadata:{review_publish_claim:{expires_at:new Date(Date.now()+60000).toISOString()}}};assert.equal(reviewPublishLocked(locked,'02_EDITED'),true);assert.equal(validateUploadRequest(locked,editor,{stage:'02_EDITED',serviceCode:'photos',filename:'edit.jpg',sizeBytes:1234}).status,409);assert.equal(validateUploadRequest(locked,agent,{stage:'04_REFERENCE',filename:'brief.pdf',sizeBytes:1234}).ok,true);assert.equal(validateUploadRequest(task,photographer,{stage:'01_RAW',serviceCode:'photos',filename:'raw.cr3'}).status,400);assert.equal(validateUploadRequest(task,photographer,{stage:'01_RAW',serviceCode:'photos',filename:'raw.cr3',sizeBytes:0}).status,400);assert.equal(validateUploadRequest(task,photographer,{stage:'01_RAW',serviceCode:'photos',filename:'raw.cr3',sizeBytes:101*1024*1024*1024}).status,413)});

test('large-file thresholds and deterministic collision path are safe',()=>{assert.equal(LARGE_UPLOAD_THRESHOLD,150*1024*1024);assert.equal(UPLOAD_CHUNK_SIZE,16*1024*1024);assert.ok(UPLOAD_CHUNK_SIZE<LARGE_UPLOAD_THRESHOLD);const original='/Northlight/NL-1/01_RAW/VIDEO/walkthrough.mov',alternate=alternateUploadPath(original);assert.notEqual(alternate,original);assert.ok(alternate.startsWith('/Northlight/NL-1/01_RAW/VIDEO/walkthrough - '));assert.ok(alternate.endsWith('.mov'))});

test('revision request is one server-side atomic command',async()=>{const status=await readFile(new URL('../functions/api/tasks/[id]/status.js',import.meta.url),'utf8'),ux=await readFile(new URL('../assets/ux-runtime.js',import.meta.url),'utf8'),migration=await readFile(new URL('../supabase/migrations/20260819113000_northlight_p1_workflow_media.sql',import.meta.url),'utf8');assert.match(status,/instructions=String\(b\.instructions\|\|''\)\.trim\(\)/);assert.match(status,/rpc\/northlight_request_revision/);assert.match(ux,/action:'request_revision',instructions:note/);assert.doesNotMatch(ux,/send\('\/api\/comments'.*Revision request/s);assert.match(migration,/create or replace function public\.northlight_request_revision/);assert.match(migration,/for update;/);assert.match(migration,/insert into public\.revisions/);assert.match(migration,/insert into public\.task_comments/);assert.match(migration,/update public\.tasks/);assert.match(migration,/insert into public\.task_events/)});

test('cancel decline reassign and reschedule are guarded database transitions',async()=>{const status=await readFile(new URL('../functions/api/tasks/[id]/status.js',import.meta.url),'utf8'),schedule=await readFile(new URL('../functions/api/tasks/[id]/schedule.js',import.meta.url),'utf8'),assign=await readFile(new URL('../functions/api/tasks/[id]/assign.js',import.meta.url),'utf8'),migration=await readFile(new URL('../supabase/migrations/20260819120500_northlight_schedule_transition_rpcs.sql',import.meta.url),'utf8'),reschedule=await readFile(new URL('../supabase/migrations/20260819131500_northlight_reschedule_calendar_ensure.sql',import.meta.url),'utf8');assert.match(status,/rpc\/northlight_decline_task/);assert.match(schedule,/rpc\/northlight_cancel_task/);assert.match(assign,/rpc\/northlight_reassign_task/);assert.match(schedule,/rpc\/northlight_apply_reschedule/);assert.match(schedule,/runTaskHandoff\(env,t\.id,'calendar'\)/);assert.match(migration,/create or replace function public\.northlight_cancel_task/);assert.match(migration,/create or replace function public\.northlight_decline_task/);assert.match(migration,/create or replace function public\.northlight_reassign_task/);assert.match(migration,/for update;/);assert.match(migration,/calendar_cleanup_queue/);assert.match(migration,/status='cancelled'/);assert.match(reschedule,/create or replace function public\.northlight_apply_reschedule/);assert.match(reschedule,/p_expected_start/);assert.match(reschedule,/raise exception 'task_changed'/);assert.match(reschedule,/values\(v_task\.tenant_id,v_task\.id,'calendar','pending'/)});

test('review publication is serialized, immutable and cannot bypass the approved manifest',async()=>{const status=await readFile(new URL('../functions/api/tasks/[id]/status.js',import.meta.url),'utf8'),release=await readFile(new URL('../functions/_lib/review-release.js',import.meta.url),'utf8'),migration=await readFile(new URL('../supabase/migrations/20260819200000_northlight_immutable_review_releases.sql',import.meta.url),'utf8'),files=await readFile(new URL('../functions/api/tasks/[id]/files.js',import.meta.url),'utf8'),link=await readFile(new URL('../functions/api/files/link.js',import.meta.url),'utf8'),uploadGuard=await readFile(new URL('../supabase/migrations/20260819134000_northlight_direct_upload_intents.sql',import.meta.url),'utf8');assert.match(status,/rpc\/northlight_claim_review_publish/);assert.match(status,/rpc\/northlight_finish_review_publish/);assert.match(status,/publishReviewRelease/);assert.match(status,/recoveredSubmitReview/);assert.match(status,/recovered:true/);assert.doesNotMatch(status,/files\/delete_v2/);assert.match(release,/files\/copy_batch_v2/);assert.match(release,/provider_file_id/);assert.match(release,/provider_revision/);assert.match(release,/content_hash/);assert.match(release,/size_bytes/);assert.match(migration,/approved_release_id = p_release_id/);assert.match(migration,/approved_release_immutable/);assert.match(migration,/previous_release_id/);assert.match(files,/selected immutable release manifest/);assert.match(link,/verifyTemporaryLinkMetadata/);assert.match(uploadGuard,/direct_pending/);assert.match(uploadGuard,/review_media_upload_in_progress/)});

test('resumable upload path survives network loss, refresh and indexing retries without provider secrets in browser',async()=>{const media=await readFile(new URL('../functions/_lib/media-upload.js',import.meta.url),'utf8'),start=await readFile(new URL('../functions/api/files/upload-session/start.js',import.meta.url),'utf8'),chunk=await readFile(new URL('../functions/api/files/upload-session/[id]/chunk.js',import.meta.url),'utf8'),finish=await readFile(new URL('../functions/api/files/upload-session/[id]/finish.js',import.meta.url),'utf8'),complete=await readFile(new URL('../functions/api/files/complete-upload.js',import.meta.url),'utf8'),runtime=await readFile(new URL('../assets/certification-runtime.js',import.meta.url),'utf8'),migration=await readFile(new URL('../supabase/migrations/20260819123500_northlight_upload_resume.sql',import.meta.url),'utf8');assert.match(media,/accessToken\(env,'dropbox'\)/);assert.doesNotMatch(start,/access_token|refresh_token/i);assert.doesNotMatch(chunk,/access_token|refresh_token/i);assert.doesNotMatch(finish,/access_token|refresh_token/i);assert.match(media,/findReusableUploadSession/);assert.match(media,/status=in\.\(uploading,uploaded,done\)/);assert.match(media,/autorename:false/);assert.match(media,/strict_conflict:true/);assert.match(media,/loadIndexableUploadSession/);assert.match(media,/markUploadSessionIndexed/);assert.match(media,/upload_session_state_changed/);assert.match(chunk,/confirmedOffset/);assert.match(chunk,/providerComplete/);assert.match(finish,/alternateUploadPath/);assert.match(finish,/lookupTag==='closed'/);assert.match(finish,/getDropboxMetadata/);assert.match(complete,/markUploadSessionIndexed/);assert.match(complete,/uploadSessionId/);assert.match(runtime,/clientFingerprint/);assert.match(runtime,/uploadedBytes/);assert.match(runtime,/providerComplete/);assert.match(runtime,/uploadSessionId/);assert.match(runtime,/completedLargePaths/);assert.match(migration,/client_fingerprint/);assert.match(migration,/uploaded/);assert.match(migration,/media_upload_sessions_resume_idx/)});

test('direct uploads keep clean names, track provider truth and recover without duplicate upload',async()=>{const direct=await readFile(new URL('../functions/_lib/direct-upload.js',import.meta.url),'utf8'),link=await readFile(new URL('../functions/api/files/upload-link.js',import.meta.url),'utf8'),complete=await readFile(new URL('../functions/api/files/complete-upload.js',import.meta.url),'utf8'),runtime=await readFile(new URL('../assets/certification-runtime.js',import.meta.url),'utf8'),migration=await readFile(new URL('../supabase/migrations/20260819134000_northlight_direct_upload_intents.sql',import.meta.url),'utf8');assert.match(direct,/existing=await metadataAt\(env,v\.path\)/);assert.match(direct,/existing\?alternateUploadPath\(v\.path\):v\.path/);assert.match(direct,/dropbox_session_id:'direct'/);assert.match(direct,/status:'direct_pending'/);assert.match(link,/mode:'add'/);assert.match(link,/mode:'overwrite'/);assert.match(link,/autorename:false/);assert.match(link,/strict_conflict:true/);assert.match(complete,/findDirectIntentByPath/);assert.match(complete,/confirmDirectProviderFile/);assert.match(runtime,/directUploads/);assert.match(runtime,/direct-upload/);assert.match(migration,/direct_pending/)});

test('integration health is honest about durable reconnects without leaking provider credentials',async()=>{const link=await readFile(new URL('../functions/api/files/upload-link.js',import.meta.url),'utf8'),testRoute=await readFile(new URL('../functions/api/integrations/[provider]/test.js',import.meta.url),'utf8'),preflight=await readFile(new URL('../functions/api/preflight.js',import.meta.url),'utf8'),adminPreflight=await readFile(new URL('../functions/api/admin/preflight.js',import.meta.url),'utf8'),bootstrap=await readFile(new URL('../functions/api/bootstrap.js',import.meta.url),'utf8'),app=await readFile(new URL('../assets/app-v2.js',import.meta.url),'utf8');assert.match(link,/requireDropboxReady/);assert.match(link,/DROPBOX_RECONNECT_REQUIRED/);assert.match(link,/dropboxUploadLinkError/);assert.match(testRoute,/needsDurableReconnect/);assert.match(testRoute,/INTEGRATION_RECONNECT_REQUIRED/);assert.match(preflight,/needsReconnect/);assert.match(preflight,/criticalProviderAttention/);assert.match(adminPreflight,/refreshReady/);assert.match(bootstrap,/integrationView/);assert.match(bootstrap,/metadata&order=provider\.asc/);assert.match(app,/Reconnect required/);assert.match(app,/durable one-time setup/);assert.doesNotMatch(bootstrap,/return json\(\{[\s\S]*metadata:/)});

test('handoff recovery is participant-scoped, attempt-versioned and cleans old calendar work first',async()=>{const recovery=await readFile(new URL('../functions/api/handoffs/recover.js',import.meta.url),'utf8'),handoffs=await readFile(new URL('../functions/_lib/task-handoffs.js',import.meta.url),'utf8');assert.match(recovery,/s\.role==='photographer'/);assert.match(recovery,/s\.role==='editor'/);assert.match(recovery,/s\.role==='agent'/);assert.match(recovery,/recoverOneSystemJob/);assert.match(handoffs,/async function patchHandoff/);assert.match(handoffs,/function sameAssignment/);assert.match(handoffs,/queueCalendarCleanup/);assert.match(handoffs,/assignment_or_schedule_changed_after_calendar/);assert.match(handoffs,/assignment_changed_after_email/);assert.match(handoffs,/const cleanup=await recoverOneCalendarCleanup/);assert.match(handoffs,/status==='cancelled'/)});

test('safe test removal refuses external history and in-flight system work',async()=>{const endpoint=await readFile(new URL('../functions/api/tasks/[id]/remove.js',import.meta.url),'utf8'),migration=await readFile(new URL('../supabase/migrations/20260819134000_northlight_direct_upload_intents.sql',import.meta.url),'utf8');assert.match(endpoint,/rpc\/northlight_remove_test_task/);assert.match(migration,/calendar_cleanup_queue/);assert.match(migration,/media_upload_sessions/);assert.match(migration,/direct_pending/);assert.match(migration,/status='processing'/);assert.match(migration,/assignment_email_sent/);assert.match(migration,/set status='cancelled'/);assert.match(migration,/deleted_by_user_id=p_actor/)});

test('public errors never echo raw exception strings but preserve structured business detail',async()=>{const hidden=await error(500,'Could not load task.','database_500:{"secret":"should-not-leak"}').json();assert.deepEqual(hidden,{error:'Could not load task.'});const structured=await error(422,'Photographer is not eligible.',{missingServices:['drone']}).json();assert.deepEqual(structured,{error:'Photographer is not eligible.',detail:{missingServices:['drone']}})});

test('session-protected cross-origin mutations are rejected before authentication or database access',async()=>{const req=new Request('https://northlight.example/api/tasks',{method:'POST',headers:{origin:'https://evil.example','sec-fetch-site':'cross-site','content-type':'application/json'},body:'{}'}),result=await requireSession(req,{});assert.equal(result.error.status,403);assert.deepEqual(await result.error.json(),{error:'Request origin is not allowed.'});const unauth=await requireSession(new Request('https://northlight.example/api/tasks'),{SESSION_SECRET:'unused'});assert.equal(unauth.error.status,401)});
