import{supa,tenant,logEvent,logSync}from'./core.js';
import{userGoogleRequest}from'./user-integrations.js';

async function stateFor(env,userId,calendarId='primary'){const t=await tenant(env),x=await supa(env,'calendar_sync_state',{query:`select=*&tenant_id=eq.${t.id}&user_id=eq.${encodeURIComponent(userId)}&provider=eq.google&calendar_id=eq.${encodeURIComponent(calendarId)}&limit=1`});return x?.[0]||null}
async function saveState(env,userId,calendarId,patch={}){const t=await tenant(env),old=await stateFor(env,userId,calendarId),rec={tenant_id:t.id,user_id:userId,provider:'google',calendar_id:calendarId,sync_token:patch.sync_token??old?.sync_token??null,channel_id:patch.channel_id??old?.channel_id??null,resource_id:patch.resource_id??old?.resource_id??null,channel_expires_at:patch.channel_expires_at??old?.channel_expires_at??null,last_full_sync_at:patch.last_full_sync_at??old?.last_full_sync_at??null,last_incremental_sync_at:patch.last_incremental_sync_at??old?.last_incremental_sync_at??null,last_error:patch.last_error??null,metadata:{...(old?.metadata||{}),...(patch.metadata||{})}};const r=await supa(env,'calendar_sync_state',{method:'POST',query:'on_conflict=tenant_id,user_id,provider,calendar_id',payload:rec,prefer:'resolution=merge-duplicates,return=representation'});return r?.[0]||rec}
function iso(x){try{return x?new Date(x).toISOString():null}catch{return null}}
async function applyEvent(env,userId,event){if(!event?.id)return;const rows=await supa(env,'tasks',{query:`select=*&calendar_event_id=eq.${encodeURIComponent(event.id)}&calendar_owner_user_id=eq.${encodeURIComponent(userId)}&deleted_at=is.null&limit=1`}),task=rows?.[0];if(!task||task.archived_at||['delivered','cancelled'].includes(task.status))return;const oldStart=iso(task.scheduled_start),oldEnd=iso(task.scheduled_end),newStart=iso(event.start?.dateTime||event.start?.date),newEnd=iso(event.end?.dateTime||event.end?.date),now=new Date().toISOString();if(event.status==='cancelled'){if(task.metadata?.external_calendar_cancelled&&task.status==='reschedule_requested')return;const meta={...(task.metadata||{}),external_calendar_cancelled:true,external_calendar_changed_at:now,external_calendar_event_id:event.id};await supa(env,'tasks',{method:'PATCH',query:`id=eq.${task.id}`,payload:{status:'reschedule_requested',next_action:'The connected Google Calendar event was cancelled externally. Review, reschedule or cancel this Northlight booking.',metadata:meta},prefer:'return=minimal'});await logEvent(env,{task_id:task.id,type:'calendar_cancelled_externally',message:'Google Calendar event was cancelled externally. Northlight kept the business booking intact for review.',detail:{event_id:event.id}});return}
if((newStart&&newStart!==oldStart)||(newEnd&&newEnd!==oldEnd)){const pending=task.metadata?.external_calendar_proposed_schedule;if(pending?.start===newStart&&pending?.end===newEnd&&task.status==='reschedule_requested')return;const meta={...(task.metadata||{}),external_calendar_changed_at:now,external_calendar_html_link:event.htmlLink||task.metadata?.calendar_link||null,external_calendar_proposed_schedule:{start:newStart,end:newEnd,event_id:event.id}};await supa(env,'tasks',{method:'PATCH',query:`id=eq.${task.id}`,payload:{status:'reschedule_requested',next_action:'Google Calendar proposes a different shoot time. Review it in Northlight before changing the booking.',metadata:meta},prefer:'return=minimal'});await logEvent(env,{task_id:task.id,type:'calendar_time_change_requested_externally',message:'Google Calendar time changed externally. Northlight preserved its booked time and requires review.',detail:{current:{start:oldStart,end:oldEnd},proposed:{start:newStart,end:newEnd},event_id:event.id}})}}

async function listAll(env,userId,calendarId,params){let pageToken=null,nextSyncToken=null,count=0;do{const q=new URLSearchParams({...params,maxResults:'2500'});if(pageToken)q.set('pageToken',pageToken);const d=await userGoogleRequest(env,userId,`/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events?${q}`);for(const ev of d.items||[]){await applyEvent(env,userId,ev);count++}pageToken=d.nextPageToken||null;nextSyncToken=d.nextSyncToken||nextSyncToken}while(pageToken);return{count,nextSyncToken}}

export async function fullCalendarSync(env,userId,calendarId='primary'){const timeMin=new Date(Date.now()-90*86400000).toISOString();const r=await listAll(env,userId,calendarId,{showDeleted:'true',singleEvents:'false',timeMin});await saveState(env,userId,calendarId,{sync_token:r.nextSyncToken,last_full_sync_at:new Date().toISOString(),last_incremental_sync_at:new Date().toISOString(),last_error:null});await logSync(env,'google','inbound','calendar','full_sync',{entity_id:userId,payload:{calendarId,count:r.count}});return r}

export async function incrementalCalendarSync(env,userId,calendarId='primary'){const st=await stateFor(env,userId,calendarId);if(!st?.sync_token)return fullCalendarSync(env,userId,calendarId);try{const r=await listAll(env,userId,calendarId,{showDeleted:'true',syncToken:st.sync_token});await saveState(env,userId,calendarId,{sync_token:r.nextSyncToken||st.sync_token,last_incremental_sync_at:new Date().toISOString(),last_error:null});await logSync(env,'google','inbound','calendar','incremental_sync',{entity_id:userId,payload:{calendarId,count:r.count}});return r}catch(e){if(String(e.message).includes('410')){await saveState(env,userId,calendarId,{sync_token:null,last_error:'sync_token_invalidated'});return fullCalendarSync(env,userId,calendarId)}await saveState(env,userId,calendarId,{last_error:e.message});throw e}}

export async function startCalendarWatch(env,userId,calendarId,origin){calendarId=calendarId||'primary';await fullCalendarSync(env,userId,calendarId);const channelId=crypto.randomUUID(),webhookToken=crypto.randomUUID().replaceAll('-',''),address=`${origin}/webhooks/google-calendar`;const d=await userGoogleRequest(env,userId,`/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events/watch`,{method:'POST',body:JSON.stringify({id:channelId,type:'web_hook',address,token:webhookToken})});await saveState(env,userId,calendarId,{channel_id:d.id,resource_id:d.resourceId,channel_expires_at:d.expiration?new Date(Number(d.expiration)).toISOString():null,last_error:null,metadata:{webhook_token:webhookToken,resource_uri:d.resourceUri||null}});await logSync(env,'google','outbound','calendar','watch_started',{entity_id:userId,payload:{calendarId,channelId:d.id,expiresAt:d.expiration||null}});return d}

export async function calendarStateByChannel(env,channelId){const t=await tenant(env),x=await supa(env,'calendar_sync_state',{query:`select=*&tenant_id=eq.${t.id}&channel_id=eq.${encodeURIComponent(channelId)}&limit=1`});return x?.[0]||null}
