import{refreshWithLease}from'./oauth-refresh.js';
const enc=new TextEncoder(),dec=new TextDecoder();
export const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const publicDetail=detail=>detail&&typeof detail==='object'?detail:null;
export const error=(status,message,detail)=>json({error:message,...(publicDetail(detail)?{detail:publicDetail(detail)}:{})},status);
export async function body(req){try{return await req.json()}catch{return {}}}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=s=>Uint8Array.from(atob(String(s).replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(s.length/4)*4,'=')),c=>c.charCodeAt(0));
async function key(secret,usage=['sign']){return crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,usage)}
export async function sign(value,secret){return b64(await crypto.subtle.sign('HMAC',await key(secret),enc.encode(value)))}
export async function safeEqual(a,b){if(!a||!b||a.length!==b.length)return false;let v=0;for(let i=0;i<a.length;i++)v|=a.charCodeAt(i)^b.charCodeAt(i);return v===0}
export async function signedState(payload,secret){const raw=b64(enc.encode(JSON.stringify({...payload,exp:Date.now()+10*60*1000})));return `${raw}.${await sign(raw,secret)}`}
export async function readState(value,secret){const [raw,sig]=String(value||'').split('.');if(!raw||!sig||!await safeEqual(sig,await sign(raw,secret)))throw new Error('invalid_oauth_state');const p=JSON.parse(dec.decode(unb64(raw)));if(!p.exp||p.exp<Date.now())throw new Error('expired_oauth_state');return p}
async function aesKey(secret){const digest=await crypto.subtle.digest('SHA-256',enc.encode(secret));return crypto.subtle.importKey('raw',digest,'AES-GCM',false,['encrypt','decrypt'])}
export async function seal(value,secret){if(!value)return null;const iv=crypto.getRandomValues(new Uint8Array(12));const out=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(secret),enc.encode(String(value)));return `v1.${b64(iv)}.${b64(out)}`}
export async function unseal(value,secret){if(!value)return null;if(!String(value).startsWith('v1.'))return value;const [,iv,cipher]=value.split('.');const out=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv)},await aesKey(secret),unb64(cipher));return dec.decode(out)}
export function cookie(req,name){const m=(req.headers.get('cookie')||'').match(new RegExp(`(?:^|;\\s*)${name}=([^;]*)`));return m?decodeURIComponent(m[1]):null}
export async function makeSession(data,env){const raw=b64(enc.encode(JSON.stringify({...data,exp:Date.now()+12*60*60*1000})));return `${raw}.${await sign(raw,env.SESSION_SECRET)}`}
export async function session(req,env){try{const v=cookie(req,'nl_session'),[raw,sig]=String(v||'').split('.');if(!raw||!sig||!await safeEqual(sig,await sign(raw,env.SESSION_SECRET)))return null;const d=JSON.parse(dec.decode(unb64(raw)));if(d.exp<Date.now())return null;return d}catch{return null}}
export const sessionCookie=value=>`nl_session=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200`;
export const clearSessionCookie=()=>`nl_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;
async function pbkdf2Bits(material,salt,iterations){const k=await crypto.subtle.importKey('raw',material,'PBKDF2',false,['deriveBits']);return new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations,hash:'SHA-256'},k,256))}
async function verifyPBKDF2Chain(password,parts){const iterations=Number(parts[1]),segments=Number(parts[2]),salts=String(parts[3]||'').split('.'),hash=parts[4];if(!Number.isInteger(iterations)||iterations<60000||iterations>100000||!Number.isInteger(segments)||segments<2||segments>10||salts.length!==segments)return false;let material=enc.encode(String(password));for(const salt of salts)material=await pbkdf2Bits(material,unb64(salt),iterations);return safeEqual(b64(material),hash)}
export async function verifyPBKDF2(password,stored){try{const parts=String(stored).split('$');const [v,it,salt,hash]=parts;if(v==='pbkdf2cf')return verifyPBKDF2Chain(password,parts);if(v!=='pbkdf2'||parts.length!==4)return false;const iterations=Number(it);if(!Number.isInteger(iterations)||iterations<1||iterations>100000)return false;const bits=await pbkdf2Bits(enc.encode(String(password)),unb64(salt),iterations);return safeEqual(b64(bits),hash)}catch{return false}}
export async function supa(env,table,{method='GET',query='',payload,prefer='return=representation'}={}){const url=`${env.SUPABASE_URL}/rest/v1/${table}${query?`?${query}`:''}`;const h={apikey:env.SUPABASE_PUBLISHABLE_KEY,'x-northlight-demo-key':env.NORTHLIGHT_DEMO_KEY,'content-type':'application/json',prefer};const r=await fetch(url,{method,headers:h,body:payload===undefined?undefined:JSON.stringify(payload)});const txt=await r.text();let d=null;try{d=txt?JSON.parse(txt):null}catch{d=txt}if(!r.ok)throw new Error(`database_${r.status}:${typeof d==='string'?d:JSON.stringify(d)}`);return d}
export async function tenant(env){const x=await supa(env,'tenants',{query:'select=*&slug=eq.realcapture&limit=1'});if(!x?.[0])throw new Error('tenant_not_found');return x[0]}
export async function integration(env,provider){const t=await tenant(env),x=await supa(env,'integration_state',{query:`select=*&tenant_id=eq.${t.id}&provider=eq.${encodeURIComponent(provider)}&limit=1`});return x?.[0]||null}
async function oauthMetadata(env,{access_token,refresh_token,expires_in,metadata={}}){const m={...metadata,access_token:await seal(access_token,env.TOKEN_ENCRYPTION_KEY),access_expires_at:Date.now()+Number(expires_in||3600)*1000-60000};if(refresh_token)m.refresh_token=await seal(refresh_token,env.TOKEN_ENCRYPTION_KEY);return m}
export async function accessToken(env,provider){const i=await integration(env,provider);if(!i||i.status!=='connected')throw new Error(`${provider}_not_connected`);if(!['google','dropbox','xero'].includes(provider))throw new Error(`${provider}_token_expired`);const t=await tenant(env),owner=crypto.randomUUID();return refreshWithLease({current:i,decode:value=>unseal(value,env.TOKEN_ENCRYPTION_KEY),claim:()=>supa(env,'rpc/northlight_claim_integration_refresh',{method:'POST',payload:{p_tenant_id:t.id,p_provider:provider,p_owner:owner,p_lease_seconds:60}}),read:()=>integration(env,provider),refreshProvider:lease=>refreshProvider(env,provider,lease),finish:async(lease,d)=>{const metadata=await oauthMetadata(env,{...d,metadata:{...(lease.metadata||{})}});return supa(env,'rpc/northlight_finish_integration_refresh',{method:'POST',payload:{p_tenant_id:t.id,p_provider:provider,p_owner:owner,p_generation:Number(lease.refresh_generation||0),p_metadata:metadata}})},release:()=>supa(env,'rpc/northlight_release_integration_refresh',{method:'POST',payload:{p_tenant_id:t.id,p_provider:provider,p_owner:owner}})})}
const SAFE_PROVIDER_ERROR_CODES=new Set(['access_denied','backenderror','conditionnotmet','consent_required','expired_access_token','failed_precondition','forbidden','fullsyncrequired','gone','insufficient_scope','interaction_required','invalid','invalid_access_token','invalid_client','invalid_grant','invalid_request','invalid_scope','invalid_token','login_required','not_found','notfound','path','ratelimitexceeded','rate_limit','required','reset','server_error','synctokenexpired','temporarily_unavailable','unauthorized','unauthorized_client','unsupported_grant_type','userratelimitexceeded']);
function safeProviderErrorCode(data){const values=[typeof data?.error==='string'?data.error:null,data?.error?.status,data?.error?.errors?.[0]?.reason,data?.error_summary,data?.reason];for(const value of values){const raw=String(value||'').split(/[\/:]/,1)[0].replace(/[^a-zA-Z0-9_]/g,'').slice(0,48),normalized=raw.toLowerCase();if(SAFE_PROVIDER_ERROR_CODES.has(normalized))return normalized}return null}
function safeProviderMarker(value,fallback,max){const marker=String(value||'').toLowerCase().replace(/[^a-z0-9_]/g,'_').replace(/_+/g,'_').replace(/^_|_$/g,'').slice(0,max);return marker||fallback}
export function providerFailure(provider,status,data,stage=''){const safeProvider=safeProviderMarker(provider,'provider',24),numericStatus=Number(status),safeStatus=Number.isInteger(numericStatus)&&numericStatus>=100&&numericStatus<=599?numericStatus:0,safeStage=stage?safeProviderMarker(stage,'stage',32):'',code=safeProviderErrorCode(data),failure=new Error(`${safeProvider}_${safeStatus}${safeStage?`_${safeStage}`:''}${code?`_${code}`:''}`);Object.defineProperties(failure,{provider:{value:safeProvider},status:{value:safeStatus},providerStatus:{value:safeStatus},providerCode:{value:code},providerStage:{value:safeStage||null}});return failure}
async function safeResponseJson(response){const text=await response.text();try{return text?JSON.parse(text):{}}catch{return{}}}
async function formToken(url,params){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)}),d=await safeResponseJson(r);if(!r.ok)throw providerFailure('oauth',r.status,d,'refresh');return d}
async function refreshProvider(env,provider,i){const rt=await unseal(i.metadata?.refresh_token,env.TOKEN_ENCRYPTION_KEY);if(!rt)throw new Error(`${provider}_refresh_token_missing`);if(provider==='google'){const d=await formToken('https://oauth2.googleapis.com/token',{client_id:env.GOOGLE_WORKSPACE_CLIENT_ID||env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_WORKSPACE_CLIENT_SECRET||env.GOOGLE_CLIENT_SECRET,refresh_token:rt,grant_type:'refresh_token'});return{...d,refresh_token:rt}}if(provider==='dropbox'){const d=await formToken('https://api.dropboxapi.com/oauth2/token',{client_id:env.DROPBOX_APP_KEY,client_secret:env.DROPBOX_APP_SECRET,refresh_token:rt,grant_type:'refresh_token'});return{...d,refresh_token:rt}}const auth=btoa(`${env.XERO_CLIENT_ID}:${env.XERO_CLIENT_SECRET}`),r=await fetch('https://identity.xero.com/connect/token',{method:'POST',headers:{authorization:`Basic ${auth}`,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:rt})}),d=await safeResponseJson(r);if(!r.ok)throw providerFailure('xero',r.status,d,'refresh');return d}
export async function logEvent(env,{task_id=null,type,actor_user_id=null,message,detail={}}){const t=await tenant(env);return supa(env,'task_events',{method:'POST',payload:{tenant_id:t.id,task_id,type,actor_user_id,detail:{message,...detail}},prefer:'return=minimal'})}
export async function logSync(env,provider,direction,entity_type,event_type,{entity_id=null,payload={},error=null,status='processed'}={}){const t=await tenant(env);return supa(env,'external_sync_events',{method:'POST',payload:{tenant_id:t.id,provider,direction,entity_type,entity_id,event_type,status,payload,error},prefer:'return=minimal'})}
function sameOriginMutation(req){const method=String(req.method||'GET').toUpperCase();if(['GET','HEAD','OPTIONS'].includes(method))return true;const site=String(req.headers.get('sec-fetch-site')||'').toLowerCase();if(site&&!['same-origin','none'].includes(site))return false;const origin=req.headers.get('origin');if(origin){try{if(new URL(origin).origin!==new URL(req.url).origin)return false}catch{return false}}return true}
export async function requireSession(req,env,roles=[],options={}){if(!sameOriginMutation(req))return{error:error(403,'Request origin is not allowed.')};const s=await session(req,env);if(!s?.userId)return {error:error(401,'authentication_required')};try{const u=(await supa(env,'users',{query:`select=id,role_code,name,email,active,metadata,auth_must_change_password,credential_version&id=eq.${encodeURIComponent(s.userId)}&limit=1`}))?.[0];if(!u||u.active===false)return {error:error(401,'authentication_required')};const authVersion=Number(u.metadata?.auth_version||0),credentialVersion=Number(u.credential_version||0);if(Number(s.authVersion||0)!==authVersion||Number(s.credentialVersion||0)!==credentialVersion)return {error:error(401,'authentication_required')};const mustChangePassword=u.auth_must_change_password===true,current={...s,userId:u.id,role:u.role_code,roleLabel:s.roleLabel||u.role_code,name:u.name,email:u.email,authVersion,credentialVersion,mustChangePassword};if(mustChangePassword&&!options.allowPasswordMigration)return{error:error(428,'password_change_required',{code:'PASSWORD_CHANGE_REQUIRED'})};if(roles.length&&!roles.includes(current.role))return {error:error(403,'permission_denied')};return {session:current}}catch{return {error:error(503,'Authentication service unavailable.')}}}
export async function googleRequest(env,path,opt={}){const token=await accessToken(env,'google'),r=await fetch(`https://www.googleapis.com${path}`,{...opt,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(opt.headers||{})}}),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={}}if(!r.ok)throw providerFailure('google',r.status,d);return d}
export async function dropboxRequest(env,endpoint,payload={}){const token=await accessToken(env,'dropbox'),r=await fetch(`https://api.dropboxapi.com/2/${endpoint}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(payload)}),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={}}if(!r.ok)throw providerFailure('dropbox',r.status,d);return d}
const header=value=>String(value||'').replace(/[\r\n]+/g,' ').trim();
const htmlEsc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const normalizeLines=value=>String(value||'').replace(/\r?\n/g,'\r\n');
const emailParagraphs=value=>String(value||'').split(/\n{2,}/).map(part=>`<p style="margin:0 0 12px;font-size:14px;line-height:1.6;color:#425047;">${htmlEsc(part).replace(/\n/g,'<br>')}</p>`).join('');
const emailBoundary=value=>{const b=header(value||`northlight-${crypto.randomUUID().replace(/-/g,'')}`);if(!/^[A-Za-z0-9'()+_,./:=?-]{1,70}$/.test(b))throw new Error('invalid_email_boundary');return b};
export function emailHtml({eyebrow='Northlight - REALCAPTURE',title='Northlight update',intro='',rows=[],body='',ctaHref='https://northlight-realcapture.pages.dev/',ctaLabel='Open Northlight',footer='This message was sent by Northlight for REALCAPTURE.'}={}){
  const detailRows=(rows||[]).filter(row=>row&&row[1]!==undefined&&row[1]!==null&&String(row[1]).trim()).map(([label,value])=>`<tr><td style="padding:10px 12px;border-bottom:1px solid #e7e1d7;width:34%;font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:#718077;font-weight:700;">${htmlEsc(label)}</td><td style="padding:10px 12px;border-bottom:1px solid #e7e1d7;font-size:14px;line-height:1.45;color:#18251f;font-weight:700;">${htmlEsc(value)}</td></tr>`).join('');
  return`<!doctype html><html><body style="margin:0;padding:0;background:#f4f1ea;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;color:#18251f;"><div style="display:none;overflow:hidden;line-height:1px;opacity:0;max-height:0;max-width:0;">${htmlEsc(intro||title)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f1ea;padding:28px 12px;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#fffaf2;border:1px solid #ddd5c8;border-radius:18px;overflow:hidden;box-shadow:0 18px 48px rgba(19,42,31,.10);"><tr><td style="background:#0d3a2b;padding:22px 24px;color:#fff;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td><div style="display:inline-block;width:34px;height:34px;line-height:34px;text-align:center;border-radius:10px;background:#eff6ef;color:#0d3a2b;font-weight:900;margin-right:10px;">N</div><span style="font-weight:800;font-size:18px;vertical-align:middle;">Northlight</span></td><td align="right" style="font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#c9d9d1;">${htmlEsc(eyebrow)}</td></tr></table></td></tr><tr><td style="padding:28px 28px 8px;"><div style="font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#68766d;font-weight:800;margin-bottom:8px;">Workspace update</div><h1 style="margin:0 0 10px;font-size:28px;line-height:1.12;color:#14231c;font-weight:850;">${htmlEsc(title)}</h1>${intro?`<p style="margin:0 0 18px;font-size:15px;line-height:1.55;color:#536158;">${htmlEsc(intro)}</p>`:''}${detailRows?`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #e7e1d7;border-radius:14px;overflow:hidden;background:#fff;margin:18px 0;">${detailRows}</table>`:''}${body?`<div style="margin:16px 0 4px;">${emailParagraphs(body)}</div>`:''}<table role="presentation" cellspacing="0" cellpadding="0" style="margin:22px 0 14px;"><tr><td><a href="${htmlEsc(ctaHref)}" style="display:inline-block;background:#0d3a2b;color:#fff;text-decoration:none;font-weight:800;border-radius:12px;padding:13px 18px;">${htmlEsc(ctaLabel)}</a></td></tr></table></td></tr><tr><td style="padding:16px 28px 24px;border-top:1px solid #e7e1d7;color:#738078;font-size:12px;line-height:1.5;">${htmlEsc(footer)}</td></tr></table></td></tr></table></body></html>`}
export function buildMimeMessage(env,to,subject,text,{messageId=null,html=null,boundary=null}={}){const from=header(env.GMAIL_FROM||'me'),recipient=header(to),safeSubject=header(subject),id=messageId?header(messageId):null;if(!recipient||recipient!==String(to||'').trim())throw new Error('invalid_email_recipient');const lines=[`From: ${from}`,`To: ${recipient}`,`Subject: ${safeSubject}`,'MIME-Version: 1.0','Auto-Submitted: auto-generated','X-Auto-Response-Suppress: All'];if(id)lines.push(`Message-ID: ${id.startsWith('<')?id:`<${id}>`}`);if(!html){lines.push('Content-Type: text/plain; charset=utf-8','Content-Transfer-Encoding: 8bit');return`${lines.join('\r\n')}\r\n\r\n${normalizeLines(text)}`}const b=emailBoundary(boundary);lines.push(`Content-Type: multipart/alternative; boundary="${b}"`);return`${lines.join('\r\n')}\r\n\r\n--${b}\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n${normalizeLines(text)}\r\n--${b}\r\nContent-Type: text/html; charset=utf-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n${normalizeLines(html)}\r\n--${b}--\r\n`};
async function gmailApi(env,path,{method='GET',payload,allowMissing=false}={}){const token=await accessToken(env,'google'),r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me${path}`,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:payload===undefined?undefined:JSON.stringify(payload)}),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={}}if(allowMissing&&(r.status===404||r.status===410))return null;if(!r.ok)throw providerFailure('gmail',r.status,d);return d}
export async function gmailCreateDraft(env,to,subject,text,{messageId=null,html=null}={}){const raw=b64(enc.encode(buildMimeMessage(env,to,subject,text,{messageId,html})));return gmailApi(env,'/drafts',{method:'POST',payload:{message:{raw}}})}
export async function gmailGetDraft(env,draftId){return gmailApi(env,`/drafts/${encodeURIComponent(draftId)}`,{allowMissing:true})}
export async function gmailSendDraft(env,draftId){return gmailApi(env,'/drafts/send',{method:'POST',payload:{id:draftId}})}
export async function gmailSend(env,to,subject,text,{messageId=null,html=null}={}){const token=await accessToken(env,'google'),raw=b64(enc.encode(buildMimeMessage(env,to,subject,text,{messageId,html}))),r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({raw})}),d=await safeResponseJson(r);if(!r.ok)throw providerFailure('gmail',r.status,d);return d}
export async function issueEmail(env,subject,text,options={}){const t=await tenant(env),to=String(t.settings?.operations_email||env.DEMO_EMAIL_TO||'').trim();if(!to)return null;const html=options.html||emailHtml({title:options.title||subject,intro:options.intro||'A Northlight workspace update needs attention.',body:text,rows:options.rows||[],ctaHref:options.ctaHref||env.PUBLIC_ORIGIN||'https://northlight-realcapture.pages.dev/',ctaLabel:options.ctaLabel||'Open Northlight'});try{return await gmailSend(env,to,subject,text,{html,messageId:options.messageId||null})}catch(e){await logSync(env,'google','outbound','email','email_failed',{status:'failed',error:e.message});throw e}}
