const enc=new TextEncoder(),dec=new TextDecoder();
export const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
export const error=(status,message,detail)=>json({error:message,...(detail?{detail}: {})},status);
export async function body(req){try{return await req.json()}catch{return {}}}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=s=>Uint8Array.from(atob(String(s).replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(s.length/4)*4,'=')),c=>c.charCodeAt(0));
async function key(secret,usage=['sign']){return crypto.subtle.importKey('raw',enc.encode(secret),'HMAC',{hash:'SHA-256'},false,usage)}
export async function sign(value,secret){return b64(await crypto.subtle.sign('HMAC',await key(secret),enc.encode(value)))}
export async function safeEqual(a,b){if(!a||!b||a.length!==b.length)return false;let v=0;for(let i=0;i<a.length;i++)v|=a.charCodeAt(i)^b.charCodeAt(i);return v===0}
export async function signedState(payload,secret){const raw=b64(enc.encode(JSON.stringify({...payload,exp:Date.now()+10*60*1000})));return `${raw}.${await sign(raw,secret)}`}
export async function readState(value,secret){const [raw,sig]=String(value||'').split('.');if(!raw||!sig||!await safeEqual(sig,await sign(raw,secret)))throw new Error('invalid_oauth_state');const p=JSON.parse(dec.decode(unb64(raw)));if(!p.exp||p.exp<Date.now())throw new Error('expired_oauth_state');return p}
async function aesKey(secret){const digest=await crypto.subtle.digest('SHA-256',enc.encode(secret));return crypto.subtle.importKey('raw',digest,'AES-GCM',false,['encrypt','decrypt'])}
export async function seal(value,secret){if(!value)return null;const iv=crypto.getRandomValues(new Uint8Array(12));const out=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(secret),enc.encode(String(value)));return `v1.${b64(iv)}.${b64(out)}`}
export async function unseal(value,secret){if(!value)return null;if(!String(value).startsWith('v1.'))return value;const [,iv,cipher]=value.split('.');const out=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv)},await aesKey(secret),unb64(cipher));return dec.decode(out)}
export function cookie(req,name){const m=(req.headers.get('cookie')||'').match(new RegExp(`(?:^|;\\s*)${name}=([^;]*)`));return m?decodeURIComponent(m[1]):null}
export async function makeSession(data,env){const raw=b64(enc.encode(JSON.stringify({...data,exp:Date.now()+12*60*60*1000})));return `${raw}.${await sign(raw,env.SESSION_SECRET)}`}
export async function session(req,env){try{const v=cookie(req,'nl_session'),[raw,sig]=String(v||'').split('.');if(!raw||!sig||!await safeEqual(sig,await sign(raw,env.SESSION_SECRET)))return null;const d=JSON.parse(dec.decode(unb64(raw)));if(d.exp<Date.now())return null;return d}catch{return null}}
export const sessionCookie=value=>`nl_session=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200`;
export const clearSessionCookie=()=>`nl_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;
export async function verifyPBKDF2(password,stored){try{const [v,it,salt,hash]=String(stored).split('$');if(v!=='pbkdf2')return false;const k=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:unb64(salt),iterations:Number(it),hash:'SHA-256'},k,256);return safeEqual(b64(bits),hash)}catch{return false}}
export async function supa(env,table,{method='GET',query='',payload,prefer='return=representation'}={}){const url=`${env.SUPABASE_URL}/rest/v1/${table}${query?`?${query}`:''}`;const h={apikey:env.SUPABASE_PUBLISHABLE_KEY,'x-northlight-demo-key':env.NORTHLIGHT_DEMO_KEY,'content-type':'application/json',prefer};const r=await fetch(url,{method,headers:h,body:payload===undefined?undefined:JSON.stringify(payload)});const txt=await r.text();let d=null;try{d=txt?JSON.parse(txt):null}catch{d=txt}if(!r.ok)throw new Error(`database_${r.status}:${typeof d==='string'?d:JSON.stringify(d)}`);return d}
export async function tenant(env){const x=await supa(env,'tenants',{query:'select=*&slug=eq.realcapture&limit=1'});if(!x?.[0])throw new Error('tenant_not_found');return x[0]}
export async function integration(env,provider){const t=await tenant(env),x=await supa(env,'integration_state',{query:`select=*&tenant_id=eq.${t.id}&provider=eq.${encodeURIComponent(provider)}&limit=1`});return x?.[0]||null}
export async function saveIntegration(env,provider,patch={}){const t=await tenant(env),old=await integration(env,provider),record={tenant_id:t.id,provider,status:patch.status||old?.status||'not_connected',account_label:patch.account_label??old?.account_label??null,last_verified_at:patch.last_verified_at??old?.last_verified_at??null,metadata:{...(old?.metadata||{}),...(patch.metadata||{})}};const q='on_conflict=tenant_id,provider';const r=await supa(env,'integration_state',{method:'POST',query:q,payload:record,prefer:'resolution=merge-duplicates,return=representation'});return r?.[0]||record}
export async function storeOAuth(env,provider,{access_token,refresh_token,expires_in,account_label,metadata={}}){const m={...metadata,access_token:await seal(access_token,env.TOKEN_ENCRYPTION_KEY),access_expires_at:Date.now()+Number(expires_in||3600)*1000-60000};if(refresh_token)m.refresh_token=await seal(refresh_token,env.TOKEN_ENCRYPTION_KEY);return saveIntegration(env,provider,{status:'connected',account_label,last_verified_at:new Date().toISOString(),metadata:m})}
export async function accessToken(env,provider){const i=await integration(env,provider);if(!i||i.status!=='connected')throw new Error(`${provider}_not_connected`);const m=i.metadata||{};if(m.access_token&&Number(m.access_expires_at||0)>Date.now()+15000)return unseal(m.access_token,env.TOKEN_ENCRYPTION_KEY);if(provider==='google')return refreshGoogle(env,i);if(provider==='dropbox')return refreshDropbox(env,i);if(provider==='xero')return refreshXero(env,i);throw new Error(`${provider}_token_expired`)}
async function formToken(url,params){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)}),d=await r.json();if(!r.ok)throw new Error(`oauth_refresh_${r.status}:${JSON.stringify(d)}`);return d}
async function refreshGoogle(env,i){const rt=await unseal(i.metadata.refresh_token,env.TOKEN_ENCRYPTION_KEY);if(!rt)throw new Error('google_refresh_token_missing');const d=await formToken('https://oauth2.googleapis.com/token',{client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,refresh_token:rt,grant_type:'refresh_token'});await storeOAuth(env,'google',{...d,refresh_token:rt,account_label:i.account_label,metadata:{...i.metadata,refresh_token:i.metadata.refresh_token}});return d.access_token}
async function refreshDropbox(env,i){const rt=await unseal(i.metadata.refresh_token,env.TOKEN_ENCRYPTION_KEY);if(!rt)throw new Error('dropbox_refresh_token_missing');const d=await formToken('https://api.dropboxapi.com/oauth2/token',{client_id:env.DROPBOX_APP_KEY,client_secret:env.DROPBOX_APP_SECRET,refresh_token:rt,grant_type:'refresh_token'});await storeOAuth(env,'dropbox',{...d,refresh_token:rt,account_label:i.account_label,metadata:{...i.metadata,refresh_token:i.metadata.refresh_token}});return d.access_token}
async function refreshXero(env,i){const rt=await unseal(i.metadata.refresh_token,env.TOKEN_ENCRYPTION_KEY);if(!rt)throw new Error('xero_refresh_token_missing');const auth=btoa(`${env.XERO_CLIENT_ID}:${env.XERO_CLIENT_SECRET}`);const r=await fetch('https://identity.xero.com/connect/token',{method:'POST',headers:{authorization:`Basic ${auth}`,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:rt})}),d=await r.json();if(!r.ok)throw new Error(`xero_refresh_${r.status}:${JSON.stringify(d)}`);await storeOAuth(env,'xero',{...d,account_label:i.account_label,metadata:{...i.metadata}});return d.access_token}
export async function logEvent(env,{task_id=null,type,actor_user_id=null,message,detail={}}){const t=await tenant(env);return supa(env,'task_events',{method:'POST',payload:{tenant_id:t.id,task_id,type,actor_user_id,detail:{message,...detail}},prefer:'return=minimal'})}
export async function logSync(env,provider,direction,entity_type,event_type,{entity_id=null,payload={},error=null,status='processed'}={}){const t=await tenant(env);return supa(env,'external_sync_events',{method:'POST',payload:{tenant_id:t.id,provider,direction,entity_type,entity_id,event_type,status,payload,error},prefer:'return=minimal'})}
export async function requireSession(req,env,roles=[]){const s=await session(req,env);if(!s)return {error:error(401,'authentication_required')};if(roles.length&&!roles.includes(s.role))return {error:error(403,'permission_denied')};return {session:s}}
export async function googleRequest(env,path,opt={}){const token=await accessToken(env,'google'),r=await fetch(`https://www.googleapis.com${path}`,{...opt,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(opt.headers||{})}}),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={raw:txt}}if(!r.ok)throw new Error(`google_${r.status}:${JSON.stringify(d)}`);return d}
export async function dropboxRequest(env,endpoint,payload={}){const token=await accessToken(env,'dropbox'),r=await fetch(`https://api.dropboxapi.com/2/${endpoint}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(payload)}),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={raw:txt}}if(!r.ok)throw new Error(`dropbox_${r.status}:${JSON.stringify(d)}`);return d}
export async function gmailSend(env,to,subject,text){const token=await accessToken(env,'google'),from=env.GMAIL_FROM||'me',mime=`From: ${from}\r\nTo: ${to}\r\nSubject: ${subject}\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${text}`,raw=b64(enc.encode(mime));const r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({raw})}),d=await r.json();if(!r.ok)throw new Error(`gmail_${r.status}:${JSON.stringify(d)}`);return d}
export async function issueEmail(env,subject,text){const to=env.DEMO_EMAIL_TO;if(!to)return null;try{return await gmailSend(env,to,subject,text)}catch(e){await logSync(env,'google','outbound','email','email_failed',{status:'failed',error:e.message,payload:{to,subject}});throw e}}
