import{supa,tenant,dropboxRequest}from'./core.js';
import{alternateUploadPath}from'./media-upload.js';

function serviceFilter(v){return v.stage==='04_REFERENCE'?'service_code=is.null':`service_code=eq.${encodeURIComponent(v.service)}`}
async function rowById(env,id){return(await supa(env,'media_upload_sessions',{query:`select=*&id=eq.${encodeURIComponent(id||'')}&limit=1`}))?.[0]||null}
async function reusable(env,s,t,v,fingerprint){const fp=String(fingerprint||'').trim().slice(0,300);if(!fp)return null;return(await supa(env,'media_upload_sessions',{query:`select=*&user_id=eq.${encodeURIComponent(s.userId)}&task_id=eq.${encodeURIComponent(t.id)}&stage=eq.${encodeURIComponent(v.stage)}&${serviceFilter(v)}&filename=eq.${encodeURIComponent(v.file.name)}&size_bytes=eq.${Number(v.sizeBytes)}&client_fingerprint=eq.${encodeURIComponent(fp)}&dropbox_session_id=eq.direct&status=in.(direct_pending,uploaded,done)&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&order=created_at.desc&limit=1`}))?.[0]||null}
async function mark(env,row,status,patch={}){const rows=await supa(env,'media_upload_sessions',{method:'PATCH',query:`id=eq.${encodeURIComponent(row.id)}&status=eq.${encodeURIComponent(row.status)}`,payload:{status,...patch,updated_at:new Date().toISOString()}});return rows?.[0]||await rowById(env,row.id)}
async function providerMetadata(env,row){try{const meta=await dropboxRequest(env,'files/get_metadata',{path:row.path,include_deleted:false});if(meta?.['.tag']==='file'&&Number(meta.size)===Number(row.size_bytes))return meta;return null}catch(e){if(String(e.message).includes('dropbox_409'))return null;throw e}}
export async function findOrCreateDirectIntent(env,s,t,v,{mimeType='',fingerprint=''}={}){let row=await reusable(env,s,t,v,fingerprint),meta=null;if(row){meta=await providerMetadata(env,row);if(meta){if(row.status==='direct_pending')row=await mark(env,row,'uploaded',{uploaded_bytes:Number(row.size_bytes),last_error:null});return{row,providerComplete:true,meta}}if(['uploaded','done'].includes(row.status)){await mark(env,row,'failed',{last_error:'provider_file_missing'});row=null}}
if(!row){const tn=await tenant(env),path=alternateUploadPath(v.path),record={tenant_id:tn.id,task_id:t.id,user_id:s.userId,stage:v.stage,service_code:v.stage==='04_REFERENCE'?null:v.service,path,filename:v.file.name,size_bytes:v.sizeBytes,mime_type:String(mimeType||'').slice(0,120)||null,client_fingerprint:String(fingerprint||'').trim().slice(0,300)||null,dropbox_session_id:'direct',uploaded_bytes:0,status:'direct_pending',expires_at:new Date(Date.now()+60*60*1000).toISOString(),last_error:null},rows=await supa(env,'media_upload_sessions',{method:'POST',payload:record});row=rows?.[0]||record}return{row,providerComplete:false,meta:null}}
export async function loadDirectIntentForCompletion(env,id,s,t,path){if(!id)return null;const row=await rowById(env,id);if(!row||row.dropbox_session_id!=='direct'||row.task_id!==t.id)return null;if(row.user_id!==s.userId&&!['admin','owner'].includes(s.role))return null;if(!['direct_pending','uploaded','done'].includes(row.status))return null;if(String(row.path||'').toLowerCase()!==String(path||'').toLowerCase())return null;return row}
export async function confirmDirectProviderFile(env,row,meta){if(!row)return null;if(!meta||meta['.tag']!=='file'||Number(meta.size)!==Number(row.size_bytes))throw new Error('direct_upload_size_mismatch');if(row.status==='direct_pending')return mark(env,row,'uploaded',{uploaded_bytes:Number(meta.size),last_error:null});if(['uploaded','done'].includes(row.status))return row;throw new Error('direct_upload_not_ready')}
