import{supa,tenant,dropboxRequest,logEvent,logSync,integration}from'./core.js';

const ROOT=env=>env.DROPBOX_ROOT||'/Northlight';
async function syncState(env){const t=await tenant(env),x=await supa(env,'dropbox_sync_state',{query:`select=*&tenant_id=eq.${t.id}&root_path=eq.${encodeURIComponent(ROOT(env))}&limit=1`});return x?.[0]||null}
async function saveState(env,patch={}){const t=await tenant(env),root=ROOT(env),old=await syncState(env),cursor=patch.clearCursor?null:(Object.prototype.hasOwnProperty.call(patch,'cursor')?patch.cursor:old?.cursor??null),rec={tenant_id:t.id,account_id:patch.account_id??old?.account_id??null,root_path:root,cursor,last_webhook_at:patch.last_webhook_at??old?.last_webhook_at??null,last_sync_at:patch.last_sync_at??old?.last_sync_at??null,last_error:Object.prototype.hasOwnProperty.call(patch,'last_error')?patch.last_error:old?.last_error??null,metadata:{...(old?.metadata||{}),...(patch.metadata||{})}};const r=await supa(env,'dropbox_sync_state',{method:'POST',query:'on_conflict=tenant_id,root_path',payload:rec,prefer:'resolution=merge-duplicates,return=representation'});return r?.[0]||rec}
async function existingFile(env,tnt,path){return(await supa(env,'task_files',{query:`select=id,content_hash,revision,is_deleted,modified_at&tenant_id=eq.${tnt.id}&provider=eq.dropbox&path=eq.${encodeURIComponent(path)}&limit=1`}))?.[0]||null}
async function indexEntry(env,entry){const path=entry.path_display||entry.path_lower||'',m=String(path).match(/\/(NL-\d+)[^/]*\/([^/]+)(?:\/([^/]+))?/i);if(!m)return false;const tasks=await supa(env,'tasks',{query:`select=id,task_no&task_no=eq.${encodeURIComponent(m[1])}&limit=1`}),task=tasks?.[0];if(!task)return false;const t=await tenant(env),deleted=entry['.tag']==='deleted',isFile=entry['.tag']==='file';if(!deleted&&!isFile)return false;const name=entry.name||path.split('/').pop()||path,old=await existingFile(env,t,path),same=!!old&&Boolean(old.is_deleted)===deleted&&String(old.revision||'')===String(entry.rev||'')&&String(old.content_hash||'')===String(entry.content_hash||'');await supa(env,'task_files',{method:'POST',query:'on_conflict=tenant_id,provider,path',payload:{tenant_id:t.id,task_id:task.id,provider:'dropbox',provider_file_id:entry.id||null,path,name,file_type:entry['.tag']||null,stage:m[2]||null,service_code:m[3]?.toLowerCase()||null,size_bytes:entry.size||null,content_hash:entry.content_hash||null,revision:entry.rev||null,is_deleted:deleted,modified_at:entry.server_modified||null,metadata:{client_modified:entry.client_modified||null}},prefer:'resolution=merge-duplicates,return=minimal'});if(!same)await logEvent(env,{task_id:task.id,type:deleted?'dropbox_file_deleted':'dropbox_file_changed',message:`Dropbox ${deleted?'removed':'updated'}: ${name}`,detail:{path,stage:m[2]||null,service:m[3]||null}});return!same}
async function fullList(env){try{return await dropboxRequest(env,'files/list_folder',{path:ROOT(env),recursive:true,include_deleted:true,limit:2000})}catch(e){if(String(e.message).includes('path/not_found'))return{entries:[],cursor:null,has_more:false,root_missing:true};throw e}}

export async function syncDropbox(env,{fromWebhook=false,forceFull=false}={}){let st=await syncState(env),d,total=0,matched=0,changed=0,full=forceFull||!st?.cursor;try{do{try{if(!full&&(st?.cursor||d?.cursor))d=await dropboxRequest(env,'files/list_folder/continue',{cursor:d?.cursor||st.cursor});else d=await fullList(env)}catch(e){if(String(e.message).includes('reset')||String(e.message).includes('path/not_found')){await saveState(env,{clearCursor:true,last_error:null});st=null;full=true;d=await fullList(env)}else throw e}for(const entry of d.entries||[]){total++;const did=await indexEntry(env,entry);if(did){matched++;changed++}}await saveState(env,{cursor:d.cursor||null,last_sync_at:new Date().toISOString(),last_webhook_at:fromWebhook?new Date().toISOString():st?.last_webhook_at,last_error:null,metadata:{has_more:!!d.has_more,root_missing:!!d.root_missing}});full=false}while(d.has_more);await logSync(env,'dropbox','inbound','files',fromWebhook?'webhook_sync':'manual_sync',{payload:{total,changed,matched,rootMissing:!!d?.root_missing}});return{total,changed,matched,cursor:d?.cursor||st?.cursor||null,rootMissing:!!d?.root_missing}}catch(e){await saveState(env,{last_error:e.message,last_webhook_at:fromWebhook?new Date().toISOString():st?.last_webhook_at});await logSync(env,'dropbox','inbound','files','sync_failed',{status:'failed',error:e.message});throw e}}

export async function connectedDropboxAccount(env){const i=await integration(env,'dropbox');return{i,accountId:i?.metadata?.account_id||null}}
export async function verifyDropboxSignature(raw,signature,secret){if(!signature||!secret)return false;const enc=new TextEncoder(),key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=await crypto.subtle.sign('HMAC',key,enc.encode(raw)),hex=[...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join('');if(hex.length!==signature.length)return false;let v=0;for(let i=0;i<hex.length;i++)v|=hex.charCodeAt(i)^signature.charCodeAt(i);return v===0}
