import{supa,tenant,accessToken,integration}from'./core.js';

const ROOT=env=>env.DROPBOX_ROOT||'/Northlight';
async function dbx(token,endpoint,payload={}){const r=await fetch(`https://api.dropboxapi.com/2/${endpoint}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(payload)}),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={raw:txt}}if(!r.ok)throw new Error(`dropbox_${r.status}:${JSON.stringify(d)}`);return d}
async function loadState(env,t){return(await supa(env,'dropbox_sync_state',{query:`select=*&tenant_id=eq.${encodeURIComponent(t.id)}&root_path=eq.${encodeURIComponent(ROOT(env))}&limit=1`}))?.[0]||null}
async function saveState(env,t,old,patch={}){const cursor=patch.clearCursor?null:(Object.prototype.hasOwnProperty.call(patch,'cursor')?patch.cursor:old?.cursor??null),rec={tenant_id:t.id,account_id:patch.account_id??old?.account_id??null,root_path:ROOT(env),cursor,last_webhook_at:patch.last_webhook_at??old?.last_webhook_at??null,last_sync_at:patch.last_sync_at??old?.last_sync_at??null,last_error:Object.prototype.hasOwnProperty.call(patch,'last_error')?patch.last_error:old?.last_error??null,metadata:{...(old?.metadata||{}),...(patch.metadata||{})}};const r=await supa(env,'dropbox_sync_state',{method:'POST',query:'on_conflict=tenant_id,root_path',payload:rec,prefer:'resolution=merge-duplicates,return=representation'});return r?.[0]||rec}
async function writeSync(env,t,eventType,{status='processed',error=null,payload={}}={}){return supa(env,'external_sync_events',{method:'POST',payload:{tenant_id:t.id,provider:'dropbox',direction:'inbound',entity_type:'files',entity_id:null,event_type:eventType,status,payload,error},prefer:'return=minimal'})}
function parseEntry(entry,taskMap){const path=entry.path_display||entry.path_lower||'',m=String(path).match(/\/(NL-\d+(?:-[A-Z0-9]{4})?)[^/]*\/([^/]+)(?:\/([^/]+))?/i);if(!m)return null;const task=taskMap.get(String(m[1]).toUpperCase()),deleted=entry['.tag']==='deleted',isFile=entry['.tag']==='file';if(!task||(!deleted&&!isFile))return null;return{entry,path,task,stage:m[2]||null,service:m[3]?.toLowerCase()||null,deleted}}
async function indexPage(env,t,entries,taskMap){const mapped=(entries||[]).map(e=>parseEntry(e,taskMap)).filter(Boolean);if(!mapped.length)return{matched:0,changed:0};const taskIds=[...new Set(mapped.map(x=>x.task.id))],existing=await supa(env,'task_files',{query:`select=id,task_id,provider_file_id,path,name,file_type,stage,service_code,size_bytes,content_hash,revision,is_deleted,modified_at,metadata&tenant_id=eq.${encodeURIComponent(t.id)}&provider=eq.dropbox&task_id=in.(${taskIds.map(encodeURIComponent).join(',')})&limit=10000`}),oldMap=new Map((existing||[]).map(x=>[String(x.path||'').toLowerCase(),x])),records=[],events=[];for(const x of mapped){const e=x.entry,old=oldMap.get(String(x.path).toLowerCase()),name=e.name||x.path.split('/').pop()||x.path,same=!!old&&Boolean(old.is_deleted)===x.deleted&&String(old.revision||'')===String(e.rev||'')&&String(old.content_hash||'')===String(e.content_hash||'');records.push({tenant_id:t.id,task_id:x.task.id,provider:'dropbox',provider_file_id:e.id||old?.provider_file_id||null,path:x.path,name,file_type:e['.tag']||old?.file_type||null,stage:x.stage,service_code:x.service,size_bytes:e.size??old?.size_bytes??null,content_hash:e.content_hash??old?.content_hash??null,revision:e.rev??old?.revision??null,is_deleted:x.deleted,modified_at:e.server_modified||old?.modified_at||new Date().toISOString(),metadata:{...(old?.metadata||{}),client_modified:e.client_modified||old?.metadata?.client_modified||null}});if(!same)events.push({tenant_id:t.id,task_id:x.task.id,type:x.deleted?'dropbox_file_deleted':'dropbox_file_changed',actor_user_id:null,detail:{message:`Dropbox ${x.deleted?'removed':'updated'}: ${name}`,path:x.path,stage:x.stage,service:x.service}})}if(records.length)await supa(env,'task_files',{method:'POST',query:'on_conflict=tenant_id,provider,path',payload:records,prefer:'resolution=merge-duplicates,return=minimal'});if(events.length)await supa(env,'task_events',{method:'POST',payload:events,prefer:'return=minimal'});return{matched:mapped.length,changed:events.length}}
async function fullList(token,env){try{return await dbx(token,'files/list_folder',{path:ROOT(env),recursive:true,include_deleted:true,limit:2000})}catch(e){if(String(e.message).includes('path/not_found'))return{entries:[],cursor:null,has_more:false,root_missing:true};throw e}}

export async function syncDropbox(env,{fromWebhook=false,forceFull=false}={}){const t=await tenant(env),token=await accessToken(env,'dropbox'),tasks=await supa(env,'tasks',{query:`select=id,task_no&tenant_id=eq.${encodeURIComponent(t.id)}&deleted_at=is.null&limit=10000`}),taskMap=new Map((tasks||[]).map(x=>[String(x.task_no).toUpperCase(),x]));let st=await loadState(env,t),d,total=0,matched=0,changed=0,full=forceFull||!st?.cursor;try{do{try{if(!full&&(st?.cursor||d?.cursor))d=await dbx(token,'files/list_folder/continue',{cursor:d?.cursor||st.cursor});else d=await fullList(token,env)}catch(e){if(String(e.message).includes('reset')||String(e.message).includes('path/not_found')){st=await saveState(env,t,st,{clearCursor:true,last_error:null});full=true;d=await fullList(token,env)}else throw e}total+=(d.entries||[]).length;const page=await indexPage(env,t,d.entries||[],taskMap);matched+=page.matched;changed+=page.changed;st=await saveState(env,t,st,{cursor:d.cursor||null,last_sync_at:new Date().toISOString(),last_webhook_at:fromWebhook?new Date().toISOString():st?.last_webhook_at,last_error:null,metadata:{has_more:!!d.has_more,root_missing:!!d.root_missing}});full=false}while(d.has_more);await writeSync(env,t,fromWebhook?'webhook_sync':'manual_sync',{payload:{total,changed,matched,rootMissing:!!d?.root_missing}});return{total,changed,matched,cursor:d?.cursor||st?.cursor||null,rootMissing:!!d?.root_missing}}catch(e){try{st=await saveState(env,t,st,{last_error:e.message,last_webhook_at:fromWebhook?new Date().toISOString():st?.last_webhook_at});await writeSync(env,t,'sync_failed',{status:'failed',error:e.message})}catch{}throw e}}

export async function connectedDropboxAccount(env){const i=await integration(env,'dropbox');return{i,accountId:i?.metadata?.account_id||null}}
export async function verifyDropboxSignature(raw,signature,secret){if(!signature||!secret)return false;const enc=new TextEncoder(),key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=await crypto.subtle.sign('HMAC',key,enc.encode(raw)),hex=[...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join('');if(hex.length!==signature.length)return false;let v=0;for(let i=0;i<hex.length;i++)v|=hex.charCodeAt(i)^signature.charCodeAt(i);return v===0}
