import{supa,tenant,accessToken}from'./core.js';

export const LARGE_UPLOAD_THRESHOLD=150*1024*1024;
export const UPLOAD_CHUNK_SIZE=16*1024*1024;
const SAFE_EXTENSIONS=new Set(['jpg','jpeg','png','webp','heic','heif','tif','tiff','dng','cr2','cr3','nef','nrw','arw','raf','rw2','orf','pef','srw','gif','mp4','mov','m4v','mxf','avi','mkv','mts','m2ts','r3d','braw','wav','mp3','aac','flac','pdf','dwg','dxf','psd','psb','ai','eps','indd','doc','docx','xls','xlsx','csv','txt','rtf','zip']);

export function safeName(v){return String(v||'file').replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,' ').trim().slice(0,160)||'file'}
export function validateFilename(v){const name=safeName(v),ext=name.includes('.')?name.split('.').pop().toLowerCase():'';if(!ext||!SAFE_EXTENSIONS.has(ext))return{ok:false,name,reason:'Choose a supported property-media or reference file type.'};return{ok:true,name,ext}}
export function canTask(t,s){if(!t||t.deleted_at)return false;if(['admin','owner'].includes(s.role))return true;if(t.archived_at)return false;return(s.role==='agent'&&t.agent_user_id===s.userId)||(s.role==='photographer'&&t.photographer_user_id===s.userId)||(s.role==='editor'&&t.editor_user_id===s.userId)}
export function allowedStage(t,s,stage){if(['admin','owner'].includes(s.role))return['01_RAW','02_EDITED','03_FINAL','04_REFERENCE'].includes(stage);if(s.role==='agent'&&t.agent_user_id===s.userId)return stage==='04_REFERENCE';if(s.role==='photographer'&&t.photographer_user_id===s.userId)return['01_RAW','04_REFERENCE'].includes(stage);if(s.role==='editor'&&t.editor_user_id===s.userId)return['02_EDITED','03_FINAL','04_REFERENCE'].includes(stage);return false}
export function uploadLifecycleBlock(t){if(!t||t.deleted_at)return'not_found';if(t.archived_at)return'archived';if(['cancelled','delivered'].includes(t.status))return'closed';return null}
export async function loadTask(env,taskId){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(taskId||'')}&limit=1`}))?.[0]||null}
export function uploadPath(t,stage,serviceCode,filename){const service=String(serviceCode||'').toLowerCase(),folder=stage==='04_REFERENCE'?`${t.dropbox_path}/${stage}`:`${t.dropbox_path}/${stage}/${service.toUpperCase().replace(/[^A-Z0-9_-]/g,'_')}`;return`${folder}/${safeName(filename)}`}
export function validateUploadRequest(t,s,{stage,serviceCode,filename,sizeBytes}={}){const block=uploadLifecycleBlock(t);if(block==='not_found')return{status:404,error:'Task not found.'};if(block==='archived')return{status:409,error:'Archived tasks are read-only. Restore the task before uploading media.'};if(block==='closed')return{status:409,error:'Closed tasks cannot accept new media uploads.'};if(!canTask(t,s))return{status:404,error:'Task not found.'};const st=String(stage||''),service=String(serviceCode||'').toLowerCase();if(!allowedStage(t,s,st))return{status:403,error:'You cannot upload to this media stage.'};if(!t.dropbox_path)return{status:409,error:'Dropbox workspace is not ready for this task.'};if(st!=='04_REFERENCE'&&!(t.service_codes||[]).includes(service))return{status:400,error:'Choose a service included in this task.'};const file=validateFilename(filename);if(!file.ok)return{status:400,error:file.reason};if(sizeBytes!==undefined&&sizeBytes!==null){const n=Number(sizeBytes);if(!Number.isFinite(n)||n<=0)return{status:400,error:'The selected file is empty or its size could not be read.'};if(n>100*1024*1024*1024)return{status:413,error:'This file is over the current 100 GB Northlight upload ceiling. Add it to the task workspace in Dropbox and refresh Northlight.'}}return{ok:true,stage:st,service,file,sizeBytes:sizeBytes==null?null:Number(sizeBytes),path:uploadPath(t,st,service,file.name)}}
function correctOffset(d){const candidates=[d?.error?.correct_offset,d?.error?.incorrect_offset?.correct_offset,d?.error?.reason?.correct_offset,d?.error?.reason?.incorrect_offset?.correct_offset,d?.correct_offset];for(const v of candidates){const n=Number(v);if(Number.isSafeInteger(n)&&n>=0)return n}return null}
async function contentCall(env,endpoint,arg,bytes=new Uint8Array()){const token=await accessToken(env,'dropbox'),r=await fetch(`https://content.dropboxapi.com/2/${endpoint}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/octet-stream','dropbox-api-arg':JSON.stringify(arg)},body:bytes}),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={raw:txt}}if(!r.ok){const e=new Error(`dropbox_${endpoint}_${r.status}`);e.status=r.status;e.correctOffset=correctOffset(d);throw e}return d}
export async function startDropboxSession(env){return contentCall(env,'files/upload_session/start',{close:false})}
export async function appendDropboxSession(env,sessionId,offset,bytes){return contentCall(env,'files/upload_session/append_v2',{cursor:{session_id:sessionId,offset},close:false},bytes)}
export async function finishDropboxSession(env,sessionId,offset,path){return contentCall(env,'files/upload_session/finish',{cursor:{session_id:sessionId,offset},commit:{path,mode:'add',autorename:true,mute:false,strict_conflict:false}})}
export async function createUploadSession(env,s,t,v,mimeType=''){const tn=await tenant(env),started=await startDropboxSession(env),row={tenant_id:tn.id,task_id:t.id,user_id:s.userId,stage:v.stage,service_code:v.stage==='04_REFERENCE'?null:v.service,path:v.path,filename:v.file.name,size_bytes:v.sizeBytes,mime_type:String(mimeType||'').slice(0,120)||null,dropbox_session_id:started.session_id,uploaded_bytes:0,status:'uploading',expires_at:new Date(Date.now()+24*60*60*1000).toISOString(),last_error:null};const out=await supa(env,'media_upload_sessions',{method:'POST',payload:row});return out?.[0]||row}
export async function loadUploadSession(env,id,s){const row=(await supa(env,'media_upload_sessions',{query:`select=*&id=eq.${encodeURIComponent(id||'')}&limit=1`}))?.[0];if(!row)return null;if(row.user_id!==s.userId&&!['admin','owner'].includes(s.role))return null;const t=await loadTask(env,row.task_id);if(!t||!canTask(t,s)&&!['admin','owner'].includes(s.role))return null;return{row,t,blocked:uploadLifecycleBlock(t)}}
export async function stopUploadSession(env,row,reason){if(row?.status==='uploading')await supa(env,'media_upload_sessions',{method:'PATCH',query:`id=eq.${encodeURIComponent(row.id)}`,payload:{status:'failed',updated_at:new Date().toISOString(),last_error:String(reason||'task_state_changed').slice(0,500)},prefer:'return=minimal'})}
export async function markUploadSessionFinished(env,row,meta){const actualPath=meta.path_display||meta.path_lower||row.path;await supa(env,'media_upload_sessions',{method:'PATCH',query:`id=eq.${encodeURIComponent(row.id)}`,payload:{status:'done',uploaded_bytes:row.size_bytes,path:actualPath,updated_at:new Date().toISOString(),last_error:null},prefer:'return=minimal'});return{actualPath,name:meta.name||row.filename,sizeBytes:meta.size||row.size_bytes}}
