import{supa,tenant,accessToken,logEvent}from'./core.js';

export const LARGE_UPLOAD_THRESHOLD=150*1024*1024;
export const UPLOAD_CHUNK_SIZE=16*1024*1024;
const SAFE_EXTENSIONS=new Set(['jpg','jpeg','png','webp','heic','tif','tiff','dng','cr2','cr3','nef','nrw','arw','raf','rw2','orf','pef','srw','mp4','mov','m4v','mxf','avi','wav','mp3','aac','pdf','dwg','dxf','doc','docx','xls','xlsx','csv','txt','rtf','zip']);

export function safeName(v){return String(v||'file').replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,' ').trim().slice(0,160)||'file'}
export function validateFilename(v){const name=safeName(v),ext=name.includes('.')?name.split('.').pop().toLowerCase():'';if(!ext||!SAFE_EXTENSIONS.has(ext))return{ok:false,name,reason:'Choose a supported property-media or reference file type.'};return{ok:true,name,ext}}
export function canTask(t,s){if(!t||t.deleted_at)return false;if(['admin','owner'].includes(s.role))return true;if(t.archived_at)return false;return(s.role==='agent'&&t.agent_user_id===s.userId)||(s.role==='photographer'&&t.photographer_user_id===s.userId)||(s.role==='editor'&&t.editor_user_id===s.userId)}
export function allowedStage(t,s,stage){if(['admin','owner'].includes(s.role))return['01_RAW','02_EDITED','03_FINAL','04_REFERENCE'].includes(stage);if(s.role==='agent'&&t.agent_user_id===s.userId)return stage==='04_REFERENCE';if(s.role==='photographer'&&t.photographer_user_id===s.userId)return['01_RAW','04_REFERENCE'].includes(stage);if(s.role==='editor'&&t.editor_user_id===s.userId)return['02_EDITED','03_FINAL','04_REFERENCE'].includes(stage);return false}
export async function loadTask(env,taskId){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(taskId||'')}&limit=1`}))?.[0]||null}
export function uploadPath(t,stage,serviceCode,filename){const service=String(serviceCode||'').toLowerCase(),folder=stage==='04_REFERENCE'?`${t.dropbox_path}/${stage}`:`${t.dropbox_path}/${stage}/${service.toUpperCase().replace(/[^A-Z0-9_-]/g,'_')}`;return`${folder}/${safeName(filename)}`}
export function validateUploadRequest(t,s,{stage,serviceCode,filename,sizeBytes}={}){if(!t||!canTask(t,s))return{status:404,error:'Task not found.'};if(t.archived_at)return{status:409,error:'Archived tasks are read-only. Restore the task before uploading media.'};const st=String(stage||''),service=String(serviceCode||'').toLowerCase();if(!allowedStage(t,s,st))return{status:403,error:'You cannot upload to this media stage.'};if(!t.dropbox_path)return{status:409,error:'Dropbox workspace is not ready for this task.'};if(st!=='04_REFERENCE'&&!(t.service_codes||[]).includes(service))return{status:400,error:'Choose a service included in this task.'};const file=validateFilename(filename);if(!file.ok)return{status:400,error:file.reason};if(sizeBytes!==undefined&&sizeBytes!==null){const n=Number(sizeBytes);if(!Number.isFinite(n)||n<=0)return{status:400,error:'The selected file is empty or its size could not be read.'};if(n>100*1024*1024*1024)return{status:413,error:'This file is over the current 100 GB Northlight upload ceiling. Add it to the task workspace in Dropbox and refresh Northlight.'}}return{ok:true,stage:st,service,file,sizeBytes:sizeBytes==null?null:Number(sizeBytes),path:uploadPath(t,st,service,file.name)}}
async function contentCall(env,endpoint,arg,bytes=new Uint8Array()){const token=await accessToken(env,'dropbox'),r=await fetch(`https://content.dropboxapi.com/2/${endpoint}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/octet-stream','dropbox-api-arg':JSON.stringify(arg)},body:bytes}),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={raw:txt}}if(!r.ok)throw new Error(`dropbox_${endpoint}_${r.status}`);return d}
export async function startDropboxSession(env){return contentCall(env,'files/upload_session/start',{close:false})}
export async function appendDropboxSession(env,sessionId,offset,bytes){return contentCall(env,'files/upload_session/append_v2',{cursor:{session_id:sessionId,offset},close:false},bytes)}
export async function finishDropboxSession(env,sessionId,offset,path){return contentCall(env,'files/upload_session/finish',{cursor:{session_id:sessionId,offset},commit:{path,mode:'add',autorename:true,mute:false,strict_conflict:false}})}
export async function createUploadSession(env,s,t,v,mimeType=''){const tn=await tenant(env),started=await startDropboxSession(env),row={tenant_id:tn.id,task_id:t.id,user_id:s.userId,stage:v.stage,service_code:v.stage==='04_REFERENCE'?null:v.service,path:v.path,filename:v.file.name,size_bytes:v.sizeBytes,mime_type:String(mimeType||'').slice(0,120)||null,dropbox_session_id:started.session_id,uploaded_bytes:0,status:'uploading',expires_at:new Date(Date.now()+24*60*60*1000).toISOString(),last_error:null};const out=await supa(env,'media_upload_sessions',{method:'POST',payload:row});return out?.[0]||row}
export async function loadUploadSession(env,id,s){const row=(await supa(env,'media_upload_sessions',{query:`select=*&id=eq.${encodeURIComponent(id||'')}&limit=1`}))?.[0];if(!row)return null;if(row.user_id!==s.userId&&!['admin','owner'].includes(s.role))return null;const t=await loadTask(env,row.task_id);if(!t||!canTask(t,s)&&!['admin','owner'].includes(s.role))return null;return{row,t}}
export async function recordCompletedUpload(env,s,t,row,meta){const tn=await tenant(env),stage=row.stage,service=stage==='04_REFERENCE'?null:String(row.service_code||'').toLowerCase();await supa(env,'task_files',{method:'POST',query:'on_conflict=tenant_id,provider,path',payload:{tenant_id:tn.id,task_id:t.id,provider:'dropbox',provider_file_id:meta.id||null,path:meta.path_display||row.path,name:meta.name||row.filename,file_type:meta['.tag']||'file',stage,service_code:service,size_bytes:meta.size||row.size_bytes,content_hash:meta.content_hash||null,revision:meta.rev||null,is_deleted:false,modified_at:meta.server_modified||new Date().toISOString(),metadata:{client_modified:meta.client_modified||null,uploaded_via:'northlight_resumable',upload_session_id:row.id}},prefer:'resolution=merge-duplicates,return=minimal'});await supa(env,'media_upload_sessions',{method:'PATCH',query:`id=eq.${encodeURIComponent(row.id)}`,payload:{status:'done',uploaded_bytes:row.size_bytes,updated_at:new Date().toISOString(),last_error:null},prefer:'return=minimal'});await logEvent(env,{task_id:t.id,type:'dropbox_file_uploaded',actor_user_id:s.userId,message:`Uploaded to Dropbox: ${meta.name||row.filename}`,detail:{path:meta.path_display||row.path,stage,service,resumable:true}})}
