import{requireSession,error,json,supa,tenant,integration,dropboxRequest,gmailSend,logEvent,logSync}from'../_lib/core.js';
import{userIntegration,userGoogleRequest}from'../_lib/user-integrations.js';

const TZ='Australia/Melbourne';
const ACTIVE_END=['delivered','cancelled'];
const wait=ms=>new Promise(r=>setTimeout(r,ms));

function visibleTask(t,s){if(['admin','owner'].includes(s.role))return t;const{dropbox_path,...rest}=t,meta={...(rest.metadata||{})};delete meta.dropbox_link;delete meta.dropbox_path;delete meta.xero_invoice_id;delete meta.invoice_total;return{...rest,metadata:meta}}
function filterTasks(rows,s){const alive=rows.filter(x=>!x.deleted_at);let out=[];if(['admin','owner'].includes(s.role))out=alive;else{const current=alive.filter(x=>!x.archived_at);if(s.role==='agent')out=current.filter(x=>x.agent_user_id===s.userId);else if(s.role==='photographer')out=current.filter(x=>x.photographer_user_id===s.userId);else if(s.role==='editor')out=current.filter(x=>x.editor_user_id===s.userId)}return out.map(x=>visibleTask(x,s))}
async function users(env){return supa(env,'users',{query:'select=id,role_code,name,email,phone,active,metadata&active=eq.true&order=name.asc'})}
async function taskById(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&limit=1`}))?.[0]||null}
async function taskByKey(env,tenantId,key){if(!key)return null;return(await supa(env,'tasks',{query:`select=*&tenant_id=eq.${tenantId}&idempotency_key=eq.${encodeURIComponent(key)}&limit=1`}))?.[0]||null}
async function hasEvent(env,taskId,type){return!!(await supa(env,'task_events',{query:`select=id&task_id=eq.${taskId}&type=eq.${encodeURIComponent(type)}&limit=1`}))?.[0]}

function zonedLocalToUtc(value,timeZone=TZ){const local=String(value||'').slice(0,16);if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(local))return new Date(value);const[y,mo,d,h,mi]=local.match(/\d+/g).map(Number),guess=new Date(Date.UTC(y,mo-1,d,h,mi));const parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(guess),p=Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)])),shown=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second||0),offset=shown-guess.getTime();let out=new Date(guess.getTime()-offset);const parts2=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(out),q=Object.fromEntries(parts2.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)])),shown2=Date.UTC(q.year,q.month-1,q.day,q.hour,q.minute,q.second||0),offset2=shown2-out.getTime();if(offset2!==offset)out=new Date(guess.getTime()-offset2);return out}
function localParts(date,timeZone=TZ){const parts=new Intl.DateTimeFormat('en-AU',{timeZone,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),p=Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,day:String(p.weekday||'').slice(0,3).toLowerCase(),minutes:Number(p.hour)*60+Number(p.minute)}}
function clockMin(v){const[h,m]=String(v||'').split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null}
function availabilityError(profile,start,end){const tz=profile.timezone||TZ,a=localParts(start,tz),z=localParts(end,tz),off=(profile.days_off||[]).some(x=>(typeof x==='string'?x:x?.date)===a.date);if(off)return'That photographer is marked unavailable on the selected date.';let hours=profile.working_hours?.[a.day];const special=(profile.special_days||[]).find(x=>x?.date===a.date);if(special)hours=special.closed?null:(special.hours||special.working_hours||hours);if(!hours||hours.length<2)return'That photographer is not working on the selected day.';const from=clockMin(hours[0]),to=clockMin(hours[1]);if(from===null||to===null||a.date!==z.date||a.minutes<from||z.minutes>to)return'That time falls outside the photographer’s working hours.';return null}

async function createFolderBatch(env,paths){const unique=[...new Set(paths)];let last;for(let attempt=0;attempt<3;attempt++){try{let d=await dropboxRequest(env,'files/create_folder_batch',{paths:unique,autorename:false,force_async:false});if(d?.['.tag']==='async_job_id'&&d.async_job_id){for(let i=0;i<8;i++){await wait(250+125*i);d=await dropboxRequest(env,'files/create_folder_batch/check',{async_job_id:d.async_job_id});if(d?.['.tag']!=='in_progress')break}}return d}catch(e){last=e;if(!String(e.message).includes('429')&&!String(e.message).includes('too_many_write_operations'))throw e;await wait(450*(attempt+1))}}throw last||new Error('dropbox_folder_batch_failed')}
async function createDropbox(env,t){if(t.dropbox_path)return{path:t.dropbox_path,reused:true};const root=env.DROPBOX_ROOT||'/Northlight',safe=String(`${t.task_no} - ${t.property_name}`).replace(/[\\<>:"|?*]/g,'-').replace(/\s+/g,' ').trim().slice(0,120),base=`${root}/${safe}`,paths=[root,base,...['01_RAW','02_EDITED','03_FINAL','04_REFERENCE'].map(x=>`${base}/${x}`)];for(const code of t.service_codes||[]){const s=String(code).toUpperCase().replace(/[^A-Z0-9_-]/g,'_');for(const stage of ['01_RAW','02_EDITED','03_FINAL'])paths.push(`${base}/${stage}/${s}`)}await createFolderBatch(env,paths);await dropboxRequest(env,'files/get_metadata',{path:base,include_deleted:false});await supa(env,'tasks',{method:'PATCH',query:`id=eq.${t.id}`,payload:{dropbox_path:base},prefer:'return=minimal'});if(!await hasEvent(env,t.id,'dropbox_workspace_created'))await logEvent(env,{task_id:t.id,type:'dropbox_workspace_created',message:'Secure Dropbox workspace created.',detail:{path:base}});return{path:base}}

async function providerDetails(env,userId){if(!userId)return null;const us=(await supa(env,'users',{query:`select=id,name,email,role_code,active&id=eq.${encodeURIComponent(userId)}&limit=1`}))?.[0];if(!us||us.active===false||us.role_code!=='photographer')return null;const p=(await supa(env,'provider_profiles',{query:`select=*&user_id=eq.${encodeURIComponent(userId)}&limit=1`}))?.[0];return p?{user:us,profile:p}:null}
async function providerCalendar(env,userId){if(!userId)return null;const ux=await userIntegration(env,userId,'google');if(!ux||ux.status!=='connected')return null;const p=(await supa(env,'provider_profiles',{query:`select=calendar_id,timezone&user_id=eq.${encodeURIComponent(userId)}&limit=1`}))?.[0]||{};return{userId,calendarId:p.calendar_id||'primary',timezone:p.timezone||TZ}}
async function calendarBusy(env,provider,start,end,before=0,after=0){if(!provider)return{connected:false,busy:[]};const min=new Date(start.getTime()-before*60000),max=new Date(end.getTime()+after*60000),d=await userGoogleRequest(env,provider.userId,'/calendar/v3/freeBusy',{method:'POST',body:JSON.stringify({timeMin:min.toISOString(),timeMax:max.toISOString(),timeZone:provider.timezone,items:[{id:provider.calendarId}]})});return{connected:true,busy:d.calendars?.[provider.calendarId]?.busy||[]}}
function calendarEventId(taskId){return`nl${String(taskId).replace(/-/g,'').toLowerCase()}`}
async function createCalendar(env,t,photographer){if(t.calendar_event_id)return{reused:true,id:t.calendar_event_id};const provider=await providerCalendar(env,t.photographer_user_id);if(!provider)throw new Error('photographer_calendar_not_connected');const start=new Date(t.scheduled_start),end=new Date(t.scheduled_end||start.getTime()+90*60000),id=calendarEventId(t.id),event={id,summary:`${t.task_no} · ${t.property_name}`,description:`Northlight property media task ${t.task_no}\nServices: ${(t.service_codes||[]).join(', ')}`,location:[t.address,t.suburb].filter(Boolean).join(', '),start:{dateTime:start.toISOString(),timeZone:provider.timezone},end:{dateTime:end.toISOString(),timeZone:provider.timezone},extendedProperties:{private:{northlightTaskId:t.id,northlightTaskNo:t.task_no}}};let d;try{d=await userGoogleRequest(env,provider.userId,`/calendar/v3/calendars/${encodeURIComponent(provider.calendarId)}/events?sendUpdates=none`,{method:'POST',body:JSON.stringify(event)})}catch(e){if(!String(e.message).includes('google_409'))throw e;d=await userGoogleRequest(env,provider.userId,`/calendar/v3/calendars/${encodeURIComponent(provider.calendarId)}/events/${encodeURIComponent(id)}`)}const current=await taskById(env,t.id);await supa(env,'tasks',{method:'PATCH',query:`id=eq.${t.id}`,payload:{calendar_event_id:d.id||id,calendar_owner_user_id:provider.userId,metadata:{...(current?.metadata||{}),calendar_link:d.htmlLink||current?.metadata?.calendar_link||null,calendar_id:provider.calendarId}},prefer:'return=minimal'});if(!await hasEvent(env,t.id,'calendar_event_created'))await logEvent(env,{task_id:t.id,type:'calendar_event_created',message:`Shoot event created on ${photographer?.name||'photographer'}'s connected calendar.`,detail:{event_id:d.id||id,calendar_id:provider.calendarId}});return d}
async function sendEmail(env,t,photographer){if(await hasEvent(env,t.id,'email_sent'))return{reused:true};const gx=await integration(env,'google');if(!gx||gx.status!=='connected')throw new Error('shared_email_not_connected');const candidate=String(photographer?.email||'').trim(),to=candidate&&!candidate.endsWith('.local')?candidate:env.DEMO_EMAIL_TO;if(!to)throw new Error('notification_email_missing');const subject=`${t.task_no} · New property media booking`,text=`Northlight · REALCAPTURE\n\nNew property media task\n\nProperty: ${t.property_name}\nAddress: ${t.address}, ${t.suburb}\nWhen: ${new Date(t.scheduled_start).toLocaleString('en-AU',{timeZone:TZ})}\nServices: ${(t.service_codes||[]).join(', ')}\nTask: ${t.task_no}\n\nOpen Northlight to view, confirm or raise an issue.`;const d=await gmailSend(env,to,subject,text);await logEvent(env,{task_id:t.id,type:'email_sent',message:'Assignment email sent.',detail:{to}});return d}
async function handoffs(env,t,ph,provider){const out={dropbox:'not_connected',calendar:provider?'pending':'not_connected',email:'not_connected'};const db=await integration(env,'dropbox');if(db?.status==='connected'){try{const cur=await taskById(env,t.id);await createDropbox(env,cur||t);out.dropbox='done'}catch(e){out.dropbox='attention';await logSync(env,'dropbox','outbound','task','workspace_failed',{entity_id:t.id,status:'failed',error:e.message})}}if(provider){try{const cur=await taskById(env,t.id);await createCalendar(env,cur||t,ph);out.calendar='done'}catch(e){out.calendar='attention';await logSync(env,'google','outbound','calendar','event_failed',{entity_id:t.id,status:'failed',error:e.message,payload:{photographerId:t.photographer_user_id}})}}try{await sendEmail(env,t,ph);out.email='done'}catch(e){out.email='attention';await logSync(env,'google','outbound','email','assignment_failed',{entity_id:t.id,status:'failed',error:e.message})}return out}

export async function onRequestGet({request,env}){const a=await requireSession(request,env);if(a.error)return a.error;try{const url=new URL(request.url),scope=url.searchParams.get('scope')||'active',rows=await supa(env,'tasks',{query:'select=*&deleted_at=is.null&order=created_at.desc'});let filtered=filterTasks(rows,a.session);if(['admin','owner'].includes(a.session.role)){if(scope==='active')filtered=filtered.filter(x=>!x.archived_at);else if(scope==='archived')filtered=filtered.filter(x=>!!x.archived_at)}return json({tasks:filtered,scope})}catch(e){return error(500,'Could not load tasks.',e.message)}}

export async function onRequestPost({request,env}){const a=await requireSession(request,env,['admin','owner','agent']);if(a.error)return a.error;try{const b=await request.json(),tnt=await tenant(env),property=String(b.property||'').trim(),area=String(b.area||'').trim(),sv=[...new Set((Array.isArray(b.services)?b.services:[]).map(String))],idem=String(b.idempotencyKey||'').trim().slice(0,120);if(!property)return error(400,'Property name is required.');if(!area)return error(400,'Property area is required.');if(!sv.length)return error(400,'Choose at least one service.');if(!b.photographerId)return error(422,'Choose an eligible photographer for this job.');if(!idem)return error(400,'Booking request key is missing. Please reopen the booking form.');let existing=await taskByKey(env,tnt.id,idem);if(existing){const pd=await providerDetails(env,existing.photographer_user_id),provider=await providerCalendar(env,existing.photographer_user_id),hs=await handoffs(env,existing,pd?.user,provider),fresh=await taskById(env,existing.id);return json({task:visibleTask(fresh||existing,a.session),handoffs:hs,reused:true})}
const pd=await providerDetails(env,b.photographerId);if(!pd)return error(422,'The selected photographer is not available for booking.');const missing=sv.filter(x=>!(pd.profile.service_codes||[]).includes(x));if(!(pd.profile.areas||[]).includes(area)||missing.length)return error(422,'That photographer is not configured for every requested service in this area.',{missingServices:missing,coveredAreas:pd.profile.areas||[]});const services=await supa(env,'services',{query:'select=code,duration_min,buffer_before_min,buffer_after_min,active&active=eq.true'}),serviceRows=services.filter(x=>sv.includes(x.code));if(serviceRows.length!==sv.length)return error(400,'One or more selected services are not active.');const timezone=pd.profile.timezone||TZ,start=zonedLocalToUtc(b.scheduledStart,timezone);if(Number.isNaN(start.getTime()))return error(400,'A valid shoot time is required.');const duration=serviceRows.reduce((n,x)=>n+Number(x.duration_min||0),0)||90,before=Math.max(0,...serviceRows.map(x=>Number(x.buffer_before_min||0))),after=Math.max(0,...serviceRows.map(x=>Number(x.buffer_after_min||0))),end=new Date(start.getTime()+duration*60000),hoursError=availabilityError(pd.profile,start,end);if(hoursError)return error(409,hoursError);const provider=await providerCalendar(env,b.photographerId);if(provider){const fb=await calendarBusy(env,provider,start,end,before,after);if(fb.busy.length&&!b.allowConflict)return error(409,'That photographer is busy during the selected slot. Choose another time.',{busy:fb.busy})}
let agentId=a.session.userId;if(['admin','owner'].includes(a.session.role)){const candidate=String(b.agentId||'').trim();if(candidate){const ag=(await supa(env,'users',{query:`select=id,role_code,active& id=eq.${encodeURIComponent(candidate)}&limit=1`.replace('& ','&')}))?.[0];if(!ag||ag.active===false||ag.role_code!=='agent')return error(422,'Choose a valid Agent for this property.');agentId=ag.id}else{const ag=(await supa(env,'users',{query:`select=id&tenant_id=eq.${tnt.id}&role_code=eq.agent&active=eq.true&order=created_at.asc&limit=1`}))?.[0];if(ag)agentId=ag.id}}
const num=`NL-${String(Date.now()).slice(-6)}`,rec={tenant_id:tnt.id,task_no:num,idempotency_key:idem,property_name:property,address:String(b.address||property).trim(),suburb:String(b.suburb||'').trim(),area,priority:'standard',status:'assigned',agent_user_id:agentId,photographer_user_id:b.photographerId,calendar_owner_user_id:b.photographerId,scheduled_start:start.toISOString(),scheduled_end:end.toISOString(),service_codes:sv,notes:String(b.notes||'').trim(),next_action:'Photographer needs to confirm the booking.',metadata:{source:'cloud',booking_created_at:new Date().toISOString(),created_by:a.session.userId,timezone,buffer_before_min:before,buffer_after_min:after,calendar_checked:!!provider}};let t;try{t=(await supa(env,'tasks',{method:'POST',payload:rec}))?.[0]}catch(e){if(!String(e.message).includes('409'))throw e;t=await taskByKey(env,tnt.id,idem)}if(!t)throw new Error('task_insert_failed');if(!await hasEvent(env,t.id,'task_created'))await logEvent(env,{task_id:t.id,type:'task_created',actor_user_id:a.session.userId,message:'Task created and photographer assigned.'});const hs=await handoffs(env,t,pd.user,provider),fresh=await taskById(env,t.id);return json({task:visibleTask(fresh||t,a.session),handoffs:hs,reused:false},201)}catch(e){return error(500,'Could not create task.',e.message)}}
