import{requireSession,error,json,supa,tenant,logEvent}from'../_lib/core.js';
import{userGoogleRequest}from'../_lib/user-integrations.js';

const TZ='Australia/Melbourne';
function visibleTask(t,s){if(['admin','owner'].includes(s.role))return t;const{dropbox_path,...rest}=t,meta={...(rest.metadata||{})};delete meta.dropbox_link;delete meta.dropbox_path;delete meta.xero_invoice_id;delete meta.invoice_total;return{...rest,metadata:meta}}
function filterTasks(rows,s){const alive=rows.filter(x=>!x.deleted_at);let out=[];if(['admin','owner'].includes(s.role))out=alive;else{const current=alive.filter(x=>!x.archived_at);if(s.role==='agent')out=current.filter(x=>x.agent_user_id===s.userId);else if(s.role==='photographer')out=current.filter(x=>x.photographer_user_id===s.userId);else if(s.role==='editor')out=current.filter(x=>x.editor_user_id===s.userId)}return out.map(x=>visibleTask(x,s))}
async function taskById(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&deleted_at=is.null&limit=1`}))?.[0]||null}
async function taskByKey(env,tenantId,key){if(!key)return null;return(await supa(env,'tasks',{query:`select=*&tenant_id=eq.${tenantId}&idempotency_key=eq.${encodeURIComponent(key)}&deleted_at=is.null&limit=1`}))?.[0]||null}
function zonedLocalToUtc(value,timeZone=TZ){const local=String(value||'').slice(0,16);if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(local))return new Date(value);const[y,mo,d,h,mi]=local.match(/\d+/g).map(Number),guess=new Date(Date.UTC(y,mo-1,d,h,mi));const parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(guess),p=Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)])),shown=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second||0),offset=shown-guess.getTime();let out=new Date(guess.getTime()-offset);const parts2=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(out),q=Object.fromEntries(parts2.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)])),shown2=Date.UTC(q.year,q.month-1,q.day,q.hour,q.minute,q.second||0),offset2=shown2-out.getTime();if(offset2!==offset)out=new Date(guess.getTime()-offset2);return out}
function localParts(date,timeZone=TZ){const parts=new Intl.DateTimeFormat('en-AU',{timeZone,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),p=Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,day:String(p.weekday||'').slice(0,3).toLowerCase(),minutes:Number(p.hour)*60+Number(p.minute)}}
function clockMin(v){const[h,m]=String(v||'').split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null}
function availabilityError(profile,start,end){const tz=profile.timezone||TZ,a=localParts(start,tz),z=localParts(end,tz);if((profile.days_off||[]).some(x=>(typeof x==='string'?x:x?.date)===a.date))return'That photographer is marked unavailable on the selected date.';let hours=profile.working_hours?.[a.day];const special=(profile.special_days||[]).find(x=>x?.date===a.date);if(special)hours=special.closed?null:(special.hours||special.working_hours||hours);if(!hours||hours.length<2)return'That photographer is not working on the selected day.';const from=clockMin(hours[0]),to=clockMin(hours[1]);if(from===null||to===null||a.date!==z.date||a.minutes<from||z.minutes>to)return`That time does not fit the photographer’s ${hours[0]}–${hours[1]} working window.`;return null}
async function providerDetails(env,userId){const us=(await supa(env,'users',{query:`select=id,name,email,role_code,active&id=eq.${encodeURIComponent(userId||'')}&limit=1`}))?.[0];if(!us||us.active===false||us.role_code!=='photographer')return null;const profile=(await supa(env,'provider_profiles',{query:`select=*&user_id=eq.${encodeURIComponent(userId)}&limit=1`}))?.[0];return profile?{user:us,profile}:null}
async function internalConflict(env,userId,min,max){return(await supa(env,'tasks',{query:`select=id,task_no,property_name,scheduled_start,scheduled_end&photographer_user_id=eq.${encodeURIComponent(userId)}&deleted_at=is.null&archived_at=is.null&status=neq.cancelled&scheduled_start=lt.${encodeURIComponent(max.toISOString())}&scheduled_end=gt.${encodeURIComponent(min.toISOString())}&limit=1`}))?.[0]||null}
async function googleBusy(env,userId,calendarId,timezone,min,max){try{const d=await userGoogleRequest(env,userId,'/calendar/v3/freeBusy',{method:'POST',body:JSON.stringify({timeMin:min.toISOString(),timeMax:max.toISOString(),timeZone:timezone,items:[{id:calendarId}]})});return{connected:true,busy:d.calendars?.[calendarId]?.busy||[]}}catch(e){if(String(e.message).includes('google_not_connected')||String(e.message).includes('google_refresh_token_missing'))return{connected:false,busy:[]};throw e}}

export async function onRequestGet({request,env}){const a=await requireSession(request,env);if(a.error)return a.error;try{const url=new URL(request.url),scope=url.searchParams.get('scope')||'active',rows=await supa(env,'tasks',{query:'select=*&deleted_at=is.null&order=created_at.desc'});let filtered=filterTasks(rows,a.session);if(['admin','owner'].includes(a.session.role)){if(scope==='active')filtered=filtered.filter(x=>!x.archived_at);else if(scope==='archived')filtered=filtered.filter(x=>!!x.archived_at)}return json({tasks:filtered,scope})}catch(e){return error(500,'Could not load tasks.',e.message)}}

export async function onRequestPost({request,env}){const a=await requireSession(request,env,['admin','owner','agent']);if(a.error)return a.error;try{const b=await request.json(),tnt=await tenant(env),property=String(b.property||'').trim(),area=String(b.area||'').trim(),sv=[...new Set((Array.isArray(b.services)?b.services:[]).map(String))],idem=String(b.idempotencyKey||'').trim().slice(0,120);if(!property)return error(400,'Property name is required.');if(!area)return error(400,'Property area is required.');if(!sv.length)return error(400,'Choose at least one service.');if(!b.photographerId)return error(422,'Choose an eligible photographer for this job.');if(!idem)return error(400,'Booking request key is missing. Please reopen the booking form.');const existing=await taskByKey(env,tnt.id,idem);if(existing)return json({task:visibleTask(existing,a.session),handoffs:{dropbox:existing.dropbox_path?'done':'pending',calendar:existing.calendar_event_id?'done':'pending',email:'pending'},reused:true});
const pd=await providerDetails(env,b.photographerId);if(!pd)return error(422,'The selected photographer is not available for booking.');const missing=sv.filter(x=>!(pd.profile.service_codes||[]).includes(x));if(!(pd.profile.areas||[]).includes(area)||missing.length)return error(422,'That photographer is not configured for every requested service in this area.',{missingServices:missing,coveredAreas:pd.profile.areas||[]});const services=await supa(env,'services',{query:'select=code,duration_min,buffer_before_min,buffer_after_min,active&active=eq.true'}),serviceRows=services.filter(x=>sv.includes(x.code));if(serviceRows.length!==sv.length)return error(400,'One or more selected services are not active.');const timezone=pd.profile.timezone||TZ,start=zonedLocalToUtc(b.scheduledStart,timezone);if(Number.isNaN(start.getTime()))return error(400,'A valid shoot time is required.');const duration=serviceRows.reduce((n,x)=>n+Number(x.duration_min||0),0)||90,before=Math.max(0,...serviceRows.map(x=>Number(x.buffer_before_min||0))),after=Math.max(0,...serviceRows.map(x=>Number(x.buffer_after_min||0))),end=new Date(start.getTime()+duration*60000),hoursError=availabilityError(pd.profile,start,end);if(hoursError)return error(409,hoursError);const min=new Date(start.getTime()-before*60000),max=new Date(end.getTime()+after*60000),conflict=await internalConflict(env,b.photographerId,min,max);if(conflict)return error(409,`Northlight already has ${conflict.task_no} in this photographer’s protected time window.`);const calendar=await googleBusy(env,b.photographerId,pd.profile.calendar_id||'primary',timezone,min,max);if(calendar.busy.length)return error(409,'That photographer is busy in Google Calendar during the shoot or its required buffer. Choose another time.',{busy:calendar.busy});
let agentId=a.session.role==='agent'?a.session.userId:null;if(['admin','owner'].includes(a.session.role)){const candidate=String(b.agentId||'').trim();if(candidate){const ag=(await supa(env,'users',{query:`select=id,role_code,active&id=eq.${encodeURIComponent(candidate)}&limit=1`}))?.[0];if(!ag||ag.active===false||ag.role_code!=='agent')return error(422,'Choose a valid Agent for this property.');agentId=ag.id}else{agentId=(await supa(env,'users',{query:`select=id&tenant_id=eq.${tnt.id}&role_code=eq.agent&active=eq.true&order=created_at.asc&limit=1`}))?.[0]?.id||null}}if(!agentId)return error(422,'An active Agent is required before this property can be booked.');
const num=`NL-${String(Date.now()).slice(-6)}-${crypto.randomUUID().slice(0,4).toUpperCase()}`,rec={tenant_id:tnt.id,task_no:num,idempotency_key:idem,property_name:property,address:String(b.address||property).trim(),suburb:String(b.suburb||'').trim(),area,priority:'standard',status:'assigned',agent_user_id:agentId,photographer_user_id:b.photographerId,calendar_owner_user_id:b.photographerId,scheduled_start:start.toISOString(),scheduled_end:end.toISOString(),service_codes:sv,notes:String(b.notes||'').trim(),next_action:'Photographer needs to confirm the booking.',metadata:{source:'cloud',booking_created_at:new Date().toISOString(),created_by:a.session.userId,timezone,buffer_before_min:before,buffer_after_min:after,calendar_checked:calendar.connected}};let t;try{t=(await supa(env,'tasks',{method:'POST',payload:rec}))?.[0]}catch(e){if(!String(e.message).includes('409'))throw e;t=await taskByKey(env,tnt.id,idem)}if(!t)throw new Error('task_insert_failed');if(t.id!==existing?.id)await logEvent(env,{task_id:t.id,type:'task_created',actor_user_id:a.session.userId,message:'Task created and photographer assigned.'});const fresh=await taskById(env,t.id)||t;return json({task:visibleTask(fresh,a.session),handoffs:{dropbox:'pending',calendar:calendar.connected?'pending':'not_connected',email:'pending'},reused:false},201)}catch(e){return error(500,'Could not create task.',e.message)}}
