import{requireSession,error,json,supa,logEvent}from'../../../_lib/core.js';
import{evaluateBooking,schedulingStatus}from'../../../_lib/scheduling.js';
import{queueTaskHandoff,runTaskHandoff}from'../../../_lib/task-handoffs.js';

async function task(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&deleted_at=is.null&limit=1`}))?.[0]||null}
function visibleTask(t,s){if(['admin','owner'].includes(s.role))return t;const{dropbox_path,...rest}=t,meta={...(rest.metadata||{})};delete meta.dropbox_link;delete meta.dropbox_path;delete meta.xero_invoice_id;delete meta.invoice_total;delete meta.assignment_email_to;return{...rest,metadata:meta}}
function allowed(t,s){if(['admin','owner'].includes(s.role))return['assigned','declined','confirmed','reschedule_requested'].includes(t.status);return s.role==='agent'&&t.agent_user_id===s.userId&&t.status==='declined'}

export async function onRequestPost({request,env,params}){const a=await requireSession(request,env);if(a.error)return a.error;try{const t=await task(env,params.id);if(!t||!allowed(t,a.session))return error(404,'Task is not available for reassignment.');if(t.archived_at)return error(409,'Archived tasks are read-only.');const b=await request.json(),newId=String(b.photographerId||'').trim();if(!newId||newId===t.photographer_user_id)return error(400,'Choose a different Photographer.');const duration=Math.max(1,(new Date(t.scheduled_end)-new Date(t.scheduled_start))/60000||90),d=await evaluateBooking(env,{photographerId:newId,area:t.area,serviceCodes:t.service_codes||[],start:new Date(t.scheduled_start),durationMinutes:duration,excludeTaskId:t.id,requireActiveServices:false});if(!d.available)return error(schedulingStatus(d.code),d.reason,d.missingServices?.length?{missingServices:d.missingServices}:undefined);
let cleanup='not_required';if(t.calendar_event_id&&t.calendar_owner_user_id){cleanup='pending';await queueTaskHandoff(env,t,'calendar_cancel',{payload:{calendarOwnerUserId:t.calendar_owner_user_id,calendarEventId:t.calendar_event_id,calendarId:t.metadata?.calendar_id||'primary'}});try{const c=await runTaskHandoff(env,t.id,'calendar_cancel');if(c.status==='done')cleanup='done'}catch{}}
const metadata={...(t.metadata||{}),reassigned_at:new Date().toISOString(),reassigned_by:a.session.userId,reassigned_from:t.photographer_user_id,calendar_cleanup_pending:cleanup==='pending'};delete metadata.assignment_email_user_id;delete metadata.assignment_email_to;delete metadata.assignment_email_at;delete metadata.calendar_link;delete metadata.calendar_id;await supa(env,'tasks',{method:'PATCH',query:`id=eq.${encodeURIComponent(t.id)}`,payload:{photographer_user_id:newId,calendar_owner_user_id:newId,calendar_event_id:null,status:'assigned',next_action:'Photographer needs to confirm the booking.',metadata},prefer:'return=minimal'});await logEvent(env,{task_id:t.id,type:'photographer_reassigned',actor_user_id:a.session.userId,message:`Photographer reassigned to ${d.photographer.name}.`,detail:{from:t.photographer_user_id,to:newId,calendar_cleanup:cleanup}});const updated=await task(env,t.id);return json({ok:true,task:visibleTask(updated,a.session),calendarConnected:d.connected,calendarCleanup:cleanup})}catch{return error(500,'Could not reassign Photographer.')}}
