import{requireSession,error,json,supa,logEvent,logSync}from'../../../_lib/core.js';
import{userGoogleRequest,userIntegration}from'../../../_lib/user-integrations.js';

const TZ='Australia/Melbourne';
async function task(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&deleted_at=is.null&limit=1`}))?.[0]||null}
function visibleTask(t,s){if(['admin','owner'].includes(s.role))return t;const{dropbox_path,...rest}=t,meta={...(rest.metadata||{})};delete meta.dropbox_link;delete meta.dropbox_path;delete meta.xero_invoice_id;delete meta.invoice_total;delete meta.assignment_email_to;return{...rest,metadata:meta}}
function allowed(t,s){if(['admin','owner'].includes(s.role))return['assigned','declined','confirmed','reschedule_requested'].includes(t.status);return s.role==='agent'&&t.agent_user_id===s.userId&&t.status==='declined'}
function localParts(date,timeZone=TZ){const parts=new Intl.DateTimeFormat('en-AU',{timeZone,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),p=Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,day:String(p.weekday||'').slice(0,3).toLowerCase(),minutes:Number(p.hour)*60+Number(p.minute)}}
function clockMin(v){const[h,m]=String(v||'').split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null}
function workingError(profile,start,end){const a=localParts(start,profile.timezone||TZ),z=localParts(end,profile.timezone||TZ);if((profile.days_off||[]).some(x=>(typeof x==='string'?x:x?.date)===a.date))return'The replacement photographer is unavailable on that date.';let hours=profile.working_hours?.[a.day];const special=(profile.special_days||[]).find(x=>x?.date===a.date);if(special)hours=special.closed?null:(special.hours||special.working_hours||hours);if(!hours||hours.length<2)return'The replacement photographer is not working that day.';const from=clockMin(hours[0]),to=clockMin(hours[1]);if(from===null||to===null||a.date!==z.date||a.minutes<from||z.minutes>to)return`The existing booking does not fit the replacement photographer’s ${hours[0]}–${hours[1]} working window.`;return null}
async function replacement(env,id){const u=(await supa(env,'users',{query:`select=id,name,email,role_code,active&id=eq.${encodeURIComponent(id)}&limit=1`}))?.[0];if(!u||u.active===false||u.role_code!=='photographer')return null;const profile=(await supa(env,'provider_profiles',{query:`select=*&user_id=eq.${encodeURIComponent(id)}&limit=1`}))?.[0];return profile?{u,profile}:null}
async function buffers(env,t){const rows=await supa(env,'services',{query:'select=code,buffer_before_min,buffer_after_min&active=eq.true'}),chosen=rows.filter(x=>(t.service_codes||[]).includes(x.code));return{before:Math.max(0,...chosen.map(x=>Number(x.buffer_before_min||0))),after:Math.max(0,...chosen.map(x=>Number(x.buffer_after_min||0)))}}
async function northlightConflict(env,t,newId,min,max){return(await supa(env,'tasks',{query:`select=id,task_no,property_name&photographer_user_id=eq.${encodeURIComponent(newId)}&id=neq.${encodeURIComponent(t.id)}&deleted_at=is.null&archived_at=is.null&status=neq.cancelled&scheduled_start=lt.${encodeURIComponent(max.toISOString())}&scheduled_end=gt.${encodeURIComponent(min.toISOString())}&limit=1`}))?.[0]||null}
async function googleBusy(env,userId,profile,min,max){const ix=await userIntegration(env,userId,'google');if(!ix||ix.status!=='connected')return{connected:false,busy:[]};const calendarId=profile.calendar_id||'primary',d=await userGoogleRequest(env,userId,'/calendar/v3/freeBusy',{method:'POST',body:JSON.stringify({timeMin:min.toISOString(),timeMax:max.toISOString(),timeZone:profile.timezone||TZ,items:[{id:calendarId}]})});return{connected:true,busy:d.calendars?.[calendarId]?.busy||[]}}
async function removeOldCalendar(env,t){if(!t.calendar_event_id||!t.calendar_owner_user_id)return;const ix=await userIntegration(env,t.calendar_owner_user_id,'google');if(!ix||ix.status!=='connected')return;const p=(await supa(env,'provider_profiles',{query:`select=calendar_id&user_id=eq.${encodeURIComponent(t.calendar_owner_user_id)}&limit=1`}))?.[0]||{},calendarId=p.calendar_id||'primary';try{await userGoogleRequest(env,t.calendar_owner_user_id,`/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(t.calendar_event_id)}?sendUpdates=none`,{method:'DELETE'})}catch(e){if(!String(e.message).includes('google_404')&&!String(e.message).includes('google_410'))throw e}}

export async function onRequestPost({request,env,params}){const a=await requireSession(request,env);if(a.error)return a.error;try{const t=await task(env,params.id);if(!t||!allowed(t,a.session))return error(404,'Task is not available for reassignment.');if(t.archived_at)return error(409,'Archived tasks are read-only.');const b=await request.json(),newId=String(b.photographerId||'');if(!newId||newId===t.photographer_user_id)return error(400,'Choose a different photographer.');const rp=await replacement(env,newId);if(!rp)return error(422,'Choose an active photographer.');const missing=(t.service_codes||[]).filter(x=>!(rp.profile.service_codes||[]).includes(x));if(!(rp.profile.areas||[]).includes(t.area)||missing.length)return error(422,'That photographer is not configured for this area and every requested service.');const start=new Date(t.scheduled_start),end=new Date(t.scheduled_end),wh=workingError(rp.profile,start,end);if(wh)return error(409,wh);const{before,after}=await buffers(env,t),min=new Date(start.getTime()-before*60000),max=new Date(end.getTime()+after*60000),nc=await northlightConflict(env,t,newId,min,max);if(nc)return error(409,`Northlight already has ${nc.task_no} in that photographer’s protected time window.`);const gc=await googleBusy(env,newId,rp.profile,min,max);if(gc.busy.length)return error(409,'The replacement photographer is busy in Google Calendar during this booking or its required buffer.');try{await removeOldCalendar(env,t)}catch(e){await logSync(env,'google','outbound','calendar','reassignment_cancel_failed',{entity_id:t.id,status:'failed',error:e.message});return error(502,'The previous Calendar booking could not be cleared, so Northlight did not reassign the task.')}const metadata={...(t.metadata||{}),reassigned_at:new Date().toISOString(),reassigned_by:a.session.userId,reassigned_from:t.photographer_user_id};delete metadata.assignment_email_user_id;delete metadata.assignment_email_to;await supa(env,'tasks',{method:'PATCH',query:`id=eq.${encodeURIComponent(t.id)}`,payload:{photographer_user_id:newId,calendar_owner_user_id:newId,calendar_event_id:null,status:'assigned',next_action:'Photographer needs to confirm the booking.',metadata},prefer:'return=minimal'});await logEvent(env,{task_id:t.id,type:'photographer_reassigned',actor_user_id:a.session.userId,message:`Photographer reassigned to ${rp.u.name}.`,detail:{from:t.photographer_user_id,to:newId}});const updated=await task(env,t.id);return json({ok:true,task:visibleTask(updated,a.session),calendarConnected:gc.connected})}catch(e){return error(500,'Could not reassign photographer.')}}
