import{requireSession,error,json,supa}from'../../../_lib/core.js';
import{evaluateBooking,schedulingStatus,isAtomicScheduleConflict}from'../../../_lib/scheduling.js';
import{runCalendarCleanup}from'../../../_lib/task-handoffs.js';

async function task(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&deleted_at=is.null&limit=1`}))?.[0]||null}
function visibleTask(t,s){if(['admin','owner'].includes(s.role))return t;const{dropbox_path,...rest}=t,meta={...(rest.metadata||{})};delete meta.dropbox_link;delete meta.dropbox_path;delete meta.xero_invoice_id;delete meta.invoice_total;delete meta.assignment_email_to;return{...rest,metadata:meta}}
function allowed(t,s){if(['admin','owner'].includes(s.role))return['assigned','declined','confirmed','reschedule_requested'].includes(t.status);return s.role==='agent'&&t.agent_user_id===s.userId&&t.status==='declined'}

export async function onRequestPost({request,env,params}){const a=await requireSession(request,env);if(a.error)return a.error;try{const t=await task(env,params.id);if(!t||!allowed(t,a.session))return error(404,'Task is not available for reassignment.');if(t.archived_at)return error(409,'Archived tasks are read-only.');const b=await request.json(),newId=String(b.photographerId||'').trim();if(!newId||newId===t.photographer_user_id)return error(400,'Choose a different Photographer.');const duration=Math.max(1,(new Date(t.scheduled_end)-new Date(t.scheduled_start))/60000||90),d=await evaluateBooking(env,{photographerId:newId,area:t.area,serviceCodes:t.service_codes||[],start:new Date(t.scheduled_start),durationMinutes:duration,excludeTaskId:t.id,requireActiveServices:false});if(!d.available)return error(schedulingStatus(d.code),d.reason,d.missingServices?.length?{missingServices:d.missingServices}:undefined);let transition;try{transition=await supa(env,'rpc/northlight_reassign_task',{method:'POST',payload:{p_task_id:t.id,p_actor:a.session.userId,p_new_photographer:newId}})}catch(e){const m=String(e.message||'');if(isAtomicScheduleConflict(e))return error(409,'That Photographer was booked by another request while reassignment was being saved. Choose another Photographer or time.');if(m.includes('task_not_found'))return error(404,'Task is not available for reassignment.');if(m.includes('task_archived'))return error(409,'Archived tasks are read-only.');if(m.includes('task_not_reassignable'))return error(409,'This task can no longer be reassigned.');if(m.includes('replacement_required'))return error(400,'Choose a different Photographer.');throw e}const cleanupId=transition?.calendar_cleanup_id||null;let cleanup=cleanupId?'pending':'not_required';if(cleanupId){try{const c=await runCalendarCleanup(env,cleanupId);cleanup=c.status==='done'?'done':c.status==='not_connected'?'attention':c.status}catch{cleanup='attention'}}const updated=await task(env,t.id);return json({ok:true,task:visibleTask(updated,a.session),calendarConnected:d.connected,calendarCleanup:cleanup})}catch{return error(500,'Could not reassign Photographer.')}}
