import{requireSession,error,json,supa,tenant,accessToken,gmailSend,logEvent,logSync}from'../../../_lib/core.js';
import{userGoogleRequest,userIntegration}from'../../../_lib/user-integrations.js';

const TZ='Australia/Melbourne';
async function task(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&deleted_at=is.null&limit=1`}))?.[0]||null}
async function hasEvent(env,taskId,type){return!!(await supa(env,'task_events',{query:`select=id&task_id=eq.${encodeURIComponent(taskId)}&type=eq.${encodeURIComponent(type)}&limit=1`}))?.[0]}
function canTrigger(t,s){return['admin','owner'].includes(s.role)||(s.role==='agent'&&t.agent_user_id===s.userId)}
async function dropboxApi(token,endpoint,payload={}){const r=await fetch(`https://api.dropboxapi.com/2/${endpoint}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(payload)}),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={raw:txt}}if(!r.ok)throw new Error(`dropbox_${r.status}:${JSON.stringify(d)}`);return d}
async function ensureDropbox(env,t){if(t.dropbox_path)return{status:'done',reused:true};const token=await accessToken(env,'dropbox'),root=env.DROPBOX_ROOT||'/Northlight',safe=String(`${t.task_no} - ${t.property_name}`).replace(/[\\<>:"|?*]/g,'-').replace(/\s+/g,' ').trim().slice(0,120),base=`${root}/${safe}`,paths=[root,base,...['01_RAW','02_EDITED','03_FINAL','04_REFERENCE'].map(x=>`${base}/${x}`)];for(const code of t.service_codes||[]){const s=String(code).toUpperCase().replace(/[^A-Z0-9_-]/g,'_');for(const stage of ['01_RAW','02_EDITED','03_FINAL'])paths.push(`${base}/${stage}/${s}`)}for(const path of [...new Set(paths)]){try{await dropboxApi(token,'files/create_folder_v2',{path,autorename:false})}catch(e){if(!String(e.message).includes('409'))throw e}}await dropboxApi(token,'files/get_metadata',{path:base,include_deleted:false});await supa(env,'tasks',{method:'PATCH',query:`id=eq.${t.id}`,payload:{dropbox_path:base},prefer:'return=minimal'});if(!await hasEvent(env,t.id,'dropbox_workspace_created'))await logEvent(env,{task_id:t.id,type:'dropbox_workspace_created',message:'Secure Dropbox workspace created.',detail:{path:base}});return{status:'done',path:base}}
function calendarEventId(taskId){return`nl${String(taskId).replace(/-/g,'').toLowerCase()}`}
async function ensureCalendar(env,t){if(t.calendar_event_id)return{status:'done',reused:true,id:t.calendar_event_id};const ix=await userIntegration(env,t.photographer_user_id,'google');if(!ix||ix.status!=='connected')return{status:'not_connected'};const p=(await supa(env,'provider_profiles',{query:`select=calendar_id,timezone&user_id=eq.${encodeURIComponent(t.photographer_user_id)}&limit=1`}))?.[0]||{},calendarId=p.calendar_id||'primary',timezone=p.timezone||TZ,start=new Date(t.scheduled_start),end=new Date(t.scheduled_end||start.getTime()+90*60000),id=calendarEventId(t.id),event={id,summary:`${t.task_no} · ${t.property_name}`,description:`Northlight property media task ${t.task_no}\nServices: ${(t.service_codes||[]).join(', ')}`,location:[t.address,t.suburb].filter(Boolean).join(', '),start:{dateTime:start.toISOString(),timeZone:timezone},end:{dateTime:end.toISOString(),timeZone:timezone},extendedProperties:{private:{northlightTaskId:t.id,northlightTaskNo:t.task_no}}};let d;try{d=await userGoogleRequest(env,t.photographer_user_id,`/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events?sendUpdates=none`,{method:'POST',body:JSON.stringify(event)})}catch(e){if(!String(e.message).includes('google_409'))throw e;d=await userGoogleRequest(env,t.photographer_user_id,`/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(id)}`)}const cur=await task(env,t.id);await supa(env,'tasks',{method:'PATCH',query:`id=eq.${t.id}`,payload:{calendar_event_id:d.id||id,calendar_owner_user_id:t.photographer_user_id,metadata:{...(cur?.metadata||{}),calendar_link:d.htmlLink||cur?.metadata?.calendar_link||null,calendar_id:calendarId}},prefer:'return=minimal'});if(!await hasEvent(env,t.id,'calendar_event_created'))await logEvent(env,{task_id:t.id,type:'calendar_event_created',message:'Shoot event created on the photographer’s connected calendar.',detail:{event_id:d.id||id,calendar_id:calendarId}});return{status:'done',id:d.id||id}}
async function ensureEmail(env,t){if(await hasEvent(env,t.id,'email_sent'))return{status:'done',reused:true};const ph=(await supa(env,'users',{query:`select=id,name,email&id=eq.${encodeURIComponent(t.photographer_user_id)}&limit=1`}))?.[0],tn=await tenant(env),candidate=String(ph?.email||'').trim(),fallback=String(tn.settings?.operations_email||env.DEMO_EMAIL_TO||'').trim(),to=candidate&&!candidate.endsWith('.local')?candidate:fallback;if(!to)return{status:'attention',reason:'notification_recipient_missing'};const subject=`${t.task_no} · New property media booking`,text=`Northlight · REALCAPTURE\n\nNew property media task\n\nProperty: ${t.property_name}\nAddress: ${t.address}, ${t.suburb}\nWhen: ${new Date(t.scheduled_start).toLocaleString('en-AU',{timeZone:TZ})}\nServices: ${(t.service_codes||[]).join(', ')}\nTask: ${t.task_no}\n\nOpen Northlight to view, confirm or raise an issue.`;await gmailSend(env,to,subject,text);await logEvent(env,{task_id:t.id,type:'email_sent',message:'Assignment email sent.',detail:{to}});return{status:'done',to}}

export async function onRequestPost({request,env,params}){const a=await requireSession(request,env);if(a.error)return a.error;let kind='northlight';try{const t=await task(env,params.id);if(!t||!canTrigger(t,a.session))return error(404,'Task not found.');if(t.archived_at)return error(409,'Archived tasks are read-only.');const b=await request.json();kind=String(b.kind||'');let result;if(kind==='dropbox')result=await ensureDropbox(env,t);else if(kind==='calendar')result=await ensureCalendar(env,t);else if(kind==='email')result=await ensureEmail(env,t);else return error(400,'Choose a supported task hand-off.');return json({ok:true,kind,...result})}catch(e){try{await logSync(env,['dropbox','calendar','email'].includes(kind)?kind:'northlight','outbound','task','handoff_failed',{entity_id:params.id,status:'failed',error:e.message})}catch{}return error(502,'This hand-off needs attention. The Northlight task itself is safe.')}}
