import{requireSession,error,json,supa,logEvent,logSync}from'../../../_lib/core.js';
import{userGoogleRequest,userIntegration}from'../../../_lib/user-integrations.js';

const TZ='Australia/Melbourne';
async function task(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&limit=1`}))?.[0]||null}
function canReschedule(t,s){return['admin','owner'].includes(s.role)||(s.role==='agent'&&t.agent_user_id===s.userId)||(s.role==='photographer'&&t.photographer_user_id===s.userId)}
function canCancel(t,s){return['admin','owner'].includes(s.role)||(s.role==='agent'&&t.agent_user_id===s.userId)}
function zonedLocalToUtc(value,timeZone=TZ){const local=String(value||'').slice(0,16);const[y,mo,d,h,mi]=local.match(/\d+/g)?.map(Number)||[];if(![y,mo,d,h,mi].every(Number.isFinite))return new Date(value);const guess=new Date(Date.UTC(y,mo-1,d,h,mi)),parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(guess),p=Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)])),shown=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second||0),offset=shown-guess.getTime();let out=new Date(guess.getTime()-offset);const parts2=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(out),q=Object.fromEntries(parts2.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)])),shown2=Date.UTC(q.year,q.month-1,q.day,q.hour,q.minute,q.second||0),offset2=shown2-out.getTime();if(offset2!==offset)out=new Date(guess.getTime()-offset2);return out}
function localParts(date,timeZone=TZ){const parts=new Intl.DateTimeFormat('en-AU',{timeZone,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),p=Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,day:String(p.weekday||'').slice(0,3).toLowerCase(),minutes:Number(p.hour)*60+Number(p.minute)}}
function clockMin(v){const[h,m]=String(v||'').split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null}
function hoursError(profile,start,end){const a=localParts(start,profile.timezone||TZ),z=localParts(end,profile.timezone||TZ);if((profile.days_off||[]).some(x=>(typeof x==='string'?x:x?.date)===a.date))return'That photographer is unavailable on the selected date.';let hours=profile.working_hours?.[a.day];const special=(profile.special_days||[]).find(x=>x?.date===a.date);if(special)hours=special.closed?null:(special.hours||special.working_hours||hours);if(!hours||hours.length<2)return'That photographer is not working on the selected day.';const from=clockMin(hours[0]),to=clockMin(hours[1]);if(from===null||to===null||a.date!==z.date||a.minutes<from||z.minutes>to)return`That time does not fit the photographer’s ${hours[0]}–${hours[1]} working window.`;return null}
async function rules(env,t){const profile=(await supa(env,'provider_profiles',{query:`select=*&user_id=eq.${encodeURIComponent(t.photographer_user_id)}&limit=1`}))?.[0];if(!profile)throw new Error('photographer_profile_missing');const rows=await supa(env,'services',{query:'select=code,buffer_before_min,buffer_after_min&active=eq.true'}),chosen=rows.filter(x=>(t.service_codes||[]).includes(x.code)),before=Math.max(0,...chosen.map(x=>Number(x.buffer_before_min||0))),after=Math.max(0,...chosen.map(x=>Number(x.buffer_after_min||0)));return{profile,before,after}}
async function northlightConflict(env,t,min,max){return(await supa(env,'tasks',{query:`select=id,task_no,property_name&photographer_user_id=eq.${encodeURIComponent(t.photographer_user_id)}&id=neq.${encodeURIComponent(t.id)}&deleted_at=is.null&archived_at=is.null&status=neq.cancelled&scheduled_start=lt.${encodeURIComponent(max.toISOString())}&scheduled_end=gt.${encodeURIComponent(min.toISOString())}&limit=1`}))?.[0]||null}
async function googleConflicts(env,t,profile,min,max){const ux=await userIntegration(env,t.photographer_user_id,'google');if(!ux||ux.status!=='connected')return{connected:false,events:[]};const calendarId=profile.calendar_id||'primary',q=new URLSearchParams({timeMin:min.toISOString(),timeMax:max.toISOString(),singleEvents:'true',showDeleted:'false',maxResults:'20'}),d=await userGoogleRequest(env,t.photographer_user_id,`/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events?${q}`),events=(d.items||[]).filter(e=>e.id!==t.calendar_event_id&&e.status!=='cancelled'&&e.transparency!=='transparent');return{connected:true,calendarId,events}}
function mutable(t){return t&&!t.deleted_at&&!t.archived_at}

export async function onRequestPatch({request,env,params}){const a=await requireSession(request,env);if(a.error)return a.error;try{const t=await task(env,params.id);if(!t||!canReschedule(t,a.session)||t.deleted_at)return error(404,'Task not found.');if(!mutable(t))return error(409,'Archived tasks are read-only. Restore this task before rescheduling it.');if(['delivered','cancelled'].includes(t.status))return error(409,'Closed tasks cannot be rescheduled.');const b=await request.json(),{profile,before,after}=await rules(env,t),start=zonedLocalToUtc(b.startLocal||b.start,profile.timezone||TZ),oldDuration=Math.max(1,(new Date(t.scheduled_end)-new Date(t.scheduled_start))/60000||90),end=new Date(start.getTime()+oldDuration*60000);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime()))return error(400,'A valid new time is required.');const h=hoursError(profile,start,end);if(h)return error(409,h);const min=new Date(start.getTime()-before*60000),max=new Date(end.getTime()+after*60000),localConflict=await northlightConflict(env,t,min,max);if(localConflict)return error(409,`Northlight already has ${localConflict.task_no} in this photographer’s protected time window.`);const gc=await googleConflicts(env,t,profile,min,max);if(gc.events.length)return error(409,'The photographer has another Google Calendar event during the new shoot or its required buffer.');if(t.calendar_event_id&&gc.connected){try{await userGoogleRequest(env,t.photographer_user_id,`/calendar/v3/calendars/${encodeURIComponent(gc.calendarId)}/events/${encodeURIComponent(t.calendar_event_id)}?sendUpdates=none`,{method:'PATCH',body:JSON.stringify({start:{dateTime:start.toISOString(),timeZone:profile.timezone||TZ},end:{dateTime:end.toISOString(),timeZone:profile.timezone||TZ}})});await logSync(env,'google','outbound','calendar','event_rescheduled',{entity_id:t.id,payload:{eventId:t.calendar_event_id,start:start.toISOString(),end:end.toISOString()}})}catch(e){await logSync(env,'google','outbound','calendar','reschedule_failed',{entity_id:t.id,status:'failed',error:e.message});return error(502,'Google Calendar could not be updated, so Northlight left the booking unchanged.')}}await supa(env,'tasks',{method:'PATCH',query:`id=eq.${t.id}`,payload:{scheduled_start:start.toISOString(),scheduled_end:end.toISOString(),next_action:'Photographer should review the updated booking time.',metadata:{...(t.metadata||{}),last_schedule_change_by:a.session.userId,last_schedule_change_at:new Date().toISOString()}},prefer:'return=minimal'});await logEvent(env,{task_id:t.id,type:'schedule_changed',actor_user_id:a.session.userId,message:'Shoot schedule changed in Northlight.',detail:{from:{start:t.scheduled_start,end:t.scheduled_end},to:{start:start.toISOString(),end:end.toISOString()}}});return json({ok:true,start:start.toISOString(),end:end.toISOString(),calendarConnected:gc.connected})}catch(e){return error(500,'Could not reschedule task.')}}

export async function onRequestDelete({request,env,params}){const a=await requireSession(request,env);if(a.error)return a.error;try{const t=await task(env,params.id);if(!t||!canCancel(t,a.session)||t.deleted_at)return error(404,'Task not found.');if(!mutable(t))return error(409,'Archived tasks are read-only. Restore this task before cancelling it.');if(['delivered','cancelled'].includes(t.status))return error(409,'This task is already closed.');if(t.calendar_event_id&&t.calendar_owner_user_id){const ux=await userIntegration(env,t.calendar_owner_user_id,'google');if(ux?.status==='connected'){const p=(await supa(env,'provider_profiles',{query:`select=calendar_id&user_id=eq.${encodeURIComponent(t.calendar_owner_user_id)}&limit=1`}))?.[0]||{},calendarId=p.calendar_id||'primary';try{await userGoogleRequest(env,t.calendar_owner_user_id,`/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(t.calendar_event_id)}?sendUpdates=none`,{method:'DELETE'})}catch(e){if(!String(e.message).includes('google_410')&&!String(e.message).includes('google_404')){await logSync(env,'google','outbound','calendar','cancel_failed',{entity_id:t.id,status:'failed',error:e.message});return error(502,'Google Calendar could not be cancelled, so Northlight left the task active.')}}}}await supa(env,'tasks',{method:'PATCH',query:`id=eq.${t.id}`,payload:{status:'cancelled',next_action:'No further action.',metadata:{...(t.metadata||{}),cancelled_by:a.session.userId,cancelled_at:new Date().toISOString()}},prefer:'return=minimal'});await logEvent(env,{task_id:t.id,type:'task_cancelled',actor_user_id:a.session.userId,message:'Task cancelled in Northlight.'});return json({ok:true})}catch(e){return error(500,'Could not cancel task.')}}
