import{requireSession,error,json,supa,issueEmail,integration}from'../../../_lib/core.js';
import{syncDropbox}from'../../../_lib/dropbox-sync.js';
import{publishReviewRelease}from'../../../_lib/review-release.js';
import{selectBestEditor}from'../../../_lib/editor-assignment.js';
async function task(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&limit=1`}))?.[0]||null}
function visibleTask(t,s){if(['admin','owner'].includes(s.role))return t;const{dropbox_path,...rest}=t,meta={...(rest.metadata||{})};delete meta.dropbox_link;delete meta.dropbox_path;delete meta.xero_invoice_id;delete meta.invoice_total;delete meta.assignment_email_to;delete meta.review_publish_claim;return{...rest,metadata:meta}}
function owns(t,s,role){if(['admin','owner'].includes(s.role))return true;if(role==='agent')return s.role==='agent'&&t.agent_user_id===s.userId;if(role==='photographer')return s.role==='photographer'&&t.photographer_user_id===s.userId;if(role==='editor')return s.role==='editor'&&t.editor_user_id===s.userId;return false}
async function files(env,taskId,stage){return supa(env,'task_files',{query:`select=id,path,name,service_code,revision&task_id=eq.${encodeURIComponent(taskId)}&stage=eq.${encodeURIComponent(stage)}&file_type=eq.file&is_deleted=eq.false&order=modified_at.desc`})}
async function approvedFiles(env,t){if(!t.approved_release_id)return[];return supa(env,'media_release_files',{query:`select=id,service_code&task_id=eq.${encodeURIComponent(t.id)}&release_id=eq.${encodeURIComponent(t.approved_release_id)}&order=service_code.asc,name.asc`})}
function missingCoverage(rows,services=[]){const have=new Set((rows||[]).map(x=>String(x.service_code||'').toLowerCase()).filter(Boolean));return(services||[]).filter(x=>!have.has(String(x).toLowerCase()))}
function names(codes=[]){return codes.map(x=>String(x).replaceAll('_',' ')).join(', ')}
async function notify(env,t,message){try{await issueEmail(env,`${t.task_no} · ${message}`,`${message}\n\nProperty: ${t.property_name}\nTask: ${t.task_no}\n\nOpen Northlight for the latest status.`)}catch{}}
function workflowFailure(e){const m=String(e?.message||'');if(m.includes('task_not_found'))return error(404,'Task not found.');if(m.includes('task_archived'))return error(409,'Archived tasks are read-only. Restore this task before changing its workflow.');if(m.includes('permission_denied'))return error(403,'You do not have permission to perform this workflow action.');if(m.includes('source_media_missing'))return error(409,'Source media changed before handoff. Refresh the property and confirm RAW coverage for every selected service.');if(m.includes('edited_media_missing'))return error(409,'Edited media changed before review submission. Refresh the property and confirm Edited coverage for every selected service.');if(m.includes('edited_media_unverified'))return error(409,'Dropbox metadata is still being verified for the Edited media. Refresh the files before submitting review.');if(m.includes('dropbox_workspace_missing'))return error(409,'The secure Dropbox workspace is not ready for this property yet.');if(m.includes('final_media_missing'))return error(409,'Final media changed before approval. Refresh the property and confirm Final coverage for every selected service.');if(m.includes('task_state_changed'))return error(409,'This property changed while the action was being completed. Refresh it and use the latest workflow state.');if(m.includes('review_media_upload_in_progress'))return error(409,'Finish or index the current Edited/Final upload before submitting this property for review.');if(m.includes('review_publish_busy'))return error(409,'Review media is already being published. Refresh the property shortly before trying again.');if(m.includes('review_publish_snapshot_changed'))return error(409,'Review media changed while it was being published. Editing remains unchanged; refresh the property and submit the latest media again.');if(m.includes('review_publish_claim_lost'))return error(409,'The review publication changed while it was being completed. Refresh the property and try again.');if(m.includes('review_publish_guard_required'))return error(409,'Review media must be published through the protected review workflow.');if(m.includes('unknown_workflow_action'))return error(400,'Unknown workflow action.');return null}
async function applyWorkflow(env,t,session,action,{editorId=null,publishedFiles=null}={}){return supa(env,'rpc/northlight_apply_workflow_transition',{method:'POST',payload:{p_task_id:t.id,p_actor:session.userId,p_action:action,p_editor_id:editorId,p_published_files:publishedFiles}})}
async function releaseReview(env,t,session,token){if(!token)return;try{await supa(env,'rpc/northlight_release_review_publish',{method:'POST',payload:{p_task_id:t.id,p_actor:session.userId,p_token:token}})}catch{}}
function shouldReleaseReview(error){const message=String(error?.message||'');return['no_edited_media','edited_path_invalid','edited_manifest_incomplete','edited_manifest_duplicate','review_publish_source_changed','review_publish_manifest_mismatch','review_publish_metadata_invalid','review_publish_metadata_incomplete','review_publish_folder_conflict','review_publish_snapshot_changed'].some(code=>message.includes(code))}
async function recoveredSubmitReview(env,taskId,session){try{const latest=await task(env,taskId);if(latest&&latest.status==='review'&&latest.approved_release_id&&owns(latest,session,'editor'))return json({ok:true,task:visibleTask(latest,session),message:'Review media is already published.',releaseId:latest.approved_release_id,recovered:true})}catch{}return null}
export async function onRequestPost({request,env,params}){const a=await requireSession(request,env);if(a.error)return a.error;let action='';try{let t=await task(env,params.id);if(!t||t.deleted_at)return error(404,'Task not found.');if(t.archived_at)return error(409,'Archived tasks are read-only. Restore this task before changing its workflow.');const b=await request.json();action=String(b.action||'');let transition=null,message='';
if(action==='confirm'){if(!owns(t,a.session,'photographer'))return error(403,'Only the assigned Photographer or management can confirm this booking.');if(!['assigned','reschedule_requested'].includes(t.status))return error(409,'This booking is not awaiting confirmation.');try{transition=await applyWorkflow(env,t,a.session,action)}catch(e){const r=workflowFailure(e);if(r)return r;throw e}}
else if(action==='decline'){if(!owns(t,a.session,'photographer'))return error(403,'Only the assigned Photographer or management can decline this booking.');if(!['assigned','confirmed','reschedule_requested'].includes(t.status))return error(409,'This booking can no longer be declined.');let x;try{x=await supa(env,'rpc/northlight_decline_task',{method:'POST',payload:{p_task_id:t.id,p_actor:a.session.userId}})}catch(e){const m=String(e.message||'');if(m.includes('task_not_found'))return error(404,'Task not found.');if(m.includes('task_archived'))return error(409,'Archived tasks are read-only.');if(m.includes('task_not_declineable'))return error(409,'This booking can no longer be declined. Refresh the property and try again.');if(m.includes('permission_denied'))return error(403,'You do not have permission to decline this booking.');throw e}t=await task(env,t.id);message='Photographer declined the booking.';await notify(env,t,message);return json({ok:true,task:visibleTask(t,a.session),message,calendarCleanup:x?.calendar_cleanup_id?'pending':'not_required'})}
else if(action==='source_ready'){if(!owns(t,a.session,'photographer'))return error(403,'Only the assigned Photographer or management can complete capture.');if(!['confirmed','shoot_complete','assigned'].includes(t.status))return error(409,'Source media cannot be handed to editing from the current status.');const raw=await files(env,t.id,'01_RAW'),missing=missingCoverage(raw,t.service_codes||[]);if(missing.length)return error(409,`Source media is still needed for: ${names(missing)}.`);const editorId=t.editor_user_id||await selectBestEditor(env,t.service_codes||[]);try{transition=await applyWorkflow(env,t,a.session,action,{editorId})}catch(e){const r=workflowFailure(e);if(r)return r;throw e}}
else if(action==='start_editing'){if(!owns(t,a.session,'editor'))return error(403,'Only the assigned Editor or management can start editing.');if(!['raw_received','revision'].includes(t.status))return error(409,'This task is not ready for editing.');try{transition=await applyWorkflow(env,t,a.session,action)}catch(e){const r=workflowFailure(e);if(r)return r;throw e}}
else if(action==='submit_review'){if(!owns(t,a.session,'editor'))return error(403,'Only the assigned Editor or management can submit work for review.');if(t.status==='review'&&t.approved_release_id)return json({ok:true,task:visibleTask(t,a.session),message:'Review media is already published.',releaseId:t.approved_release_id,idempotent:true});if(t.status!=='editing')return error(409,'Editing must be in progress before review.');const db=await integration(env,'dropbox');if(!db||db.status!=='connected')return error(409,'Dropbox must be connected before review media can be published.');let claim=null,token='';try{claim=await supa(env,'rpc/northlight_claim_review_publish',{method:'POST',payload:{p_task_id:t.id,p_actor:a.session.userId}});token=String(claim?.token||'')}catch(e){const r=workflowFailure(e);if(r)return r;throw e}const releaseId=String(claim?.release_id||''),releaseRoot=String(claim?.release_root||'');if(!token||!releaseId||!releaseRoot)return error(500,'Northlight could not protect this review publication.');try{const edited=Array.isArray(claim?.edited_files)?claim.edited_files:[],published=await publishReviewRelease(env,t,edited,releaseId);transition=await supa(env,'rpc/northlight_finish_review_publish',{method:'POST',payload:{p_task_id:t.id,p_actor:a.session.userId,p_token:token,p_release_id:published.releaseId,p_release_root:published.rootPath,p_manifest:published.manifest}});try{await syncDropbox(env)}catch{}}catch(e){if(shouldReleaseReview(e))await releaseReview(env,t,a.session,token);if(['no_edited_media','edited_path_invalid','edited_manifest_incomplete','edited_manifest_duplicate','review_publish_source_changed'].some(code=>String(e.message||'').includes(code)))return error(409,'Edited media changed before review publication. Refresh the property and submit the latest verified files.');if(String(e.message||'').includes('review_publish_manifest_mismatch'))return error(409,'An incomplete or changed release was found in Dropbox. Northlight kept the prior approved release and blocked this publication.');const r=workflowFailure(e);if(r)return r;return error(502,'Dropbox could not publish a complete verified release. Editing and the prior approved release are unchanged, and this action can be retried safely.')}}
else if(action==='request_revision'){if(!owns(t,a.session,'agent'))return error(403,'Only the property Agent or management can request a revision.');if(t.status!=='review')return error(409,'This task is not currently awaiting review.');const instructions=String(b.instructions||'').trim();if(instructions.length<5)return error(400,'Revision instructions are required.');if(instructions.length>4000)return error(400,'Keep revision instructions under 4,000 characters.');let revision;try{revision=await supa(env,'rpc/northlight_request_revision',{method:'POST',payload:{p_task_id:t.id,p_requested_by:a.session.userId,p_note:instructions}})}catch(e){const m=String(e.message||'');if(m.includes('task_not_in_review'))return error(409,'This task is no longer awaiting review. Refresh the property and try again.');if(m.includes('task_archived'))return error(409,'Archived tasks are read-only.');if(m.includes('permission_denied'))return error(403,'Only the property Agent or management can request a revision.');if(m.includes('revision_note_required')||m.includes('revision_note_too_long'))return error(400,'Enter clear revision instructions under 4,000 characters.');throw e}t=await task(env,t.id);message='A revision was requested.';await notify(env,t,message);return json({ok:true,task:visibleTask(t,a.session),message,revisionNumber:Number(revision?.revision_number||t.revision_count||0)})}
else if(action==='approve_delivery'){if(!owns(t,a.session,'agent'))return error(403,'Only the property Agent or management can approve delivery.');if(t.status!=='review')return error(409,'This task is not currently awaiting final review.');const final=await approvedFiles(env,t),missing=missingCoverage(final,t.service_codes||[]);if(!t.approved_release_id||missing.length)return error(409,`Approved final media is still missing${missing.length?` for: ${names(missing)}`:''}.`);try{transition=await supa(env,'rpc/northlight_approve_delivery',{method:'POST',payload:{p_task_id:t.id,p_actor:a.session.userId}})}catch(e){const r=workflowFailure(e);if(r)return r;throw e}}
else return error(400,'Unknown workflow action.');
t=await task(env,t.id);message=String(transition?.message||'Workflow updated.');await notify(env,t,message);return json({ok:true,task:visibleTask(t,a.session),message})}catch{const recovered=action==='submit_review'?await recoveredSubmitReview(env,params.id,a.session):null;if(recovered)return recovered;return error(500,'Could not update task status.')}}
