import{requireSession,error,json,supa,logEvent,issueEmail,dropboxRequest,integration}from'../../../_lib/core.js';
import{syncDropbox}from'../../../_lib/dropbox-sync.js';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function task(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&limit=1`}))?.[0]||null}
function visibleTask(t,s){if(['admin','owner'].includes(s.role))return t;const{dropbox_path,...rest}=t,meta={...(rest.metadata||{})};delete meta.dropbox_link;delete meta.dropbox_path;delete meta.xero_invoice_id;delete meta.invoice_total;delete meta.assignment_email_to;return{...rest,metadata:meta}}
function owns(t,s,role){if(['admin','owner'].includes(s.role))return true;if(role==='agent')return s.role==='agent'&&t.agent_user_id===s.userId;if(role==='photographer')return s.role==='photographer'&&t.photographer_user_id===s.userId;if(role==='editor')return s.role==='editor'&&t.editor_user_id===s.userId;return false}
async function bestEditor(env,services=[]){const[profiles,users]=await Promise.all([supa(env,'editor_profiles',{query:'select=user_id,skills,current_load'}),supa(env,'users',{query:'select=id&role_code=eq.editor&active=eq.true'})]),active=new Set(users.map(x=>x.id)),rows=profiles.filter(x=>active.has(x.user_id));if(!rows.length)return null;return rows.map(x=>({...x,score:(x.skills||[]).filter(s=>services.includes(s)).length})).sort((a,b)=>b.score-a.score||Number(a.current_load||0)-Number(b.current_load||0))[0]?.user_id||null}
async function files(env,taskId,stage){return supa(env,'task_files',{query:`select=id,path,name,service_code,revision&task_id=eq.${encodeURIComponent(taskId)}&stage=eq.${encodeURIComponent(stage)}&file_type=eq.file&is_deleted=eq.false&order=modified_at.desc`})}
function missingCoverage(rows,services=[]){const have=new Set((rows||[]).map(x=>String(x.service_code||'').toLowerCase()).filter(Boolean));return(services||[]).filter(x=>!have.has(String(x).toLowerCase()))}
function names(codes=[]){return codes.map(x=>String(x).replaceAll('_',' ')).join(', ')}
async function publishReview(env,t,edited){if(!edited?.length)throw new Error('no_edited_media');const db=await integration(env,'dropbox');if(!db||db.status!=='connected')throw new Error('dropbox_not_connected');const entries=edited.map(f=>({from_path:f.path,to_path:String(f.path).replace('/02_EDITED/','/03_FINAL/')}));let d=await dropboxRequest(env,'files/copy_batch_v2',{entries,autorename:true});if(d?.['.tag']==='async_job_id'&&d.async_job_id){for(let i=0;i<12;i++){await wait(300+120*i);d=await dropboxRequest(env,'files/copy_batch/check_v2',{async_job_id:d.async_job_id});if(d?.['.tag']!=='in_progress')break}}await syncDropbox(env);return entries.length}
async function notify(env,t,message){try{await issueEmail(env,`${t.task_no} · ${message}`,`${message}\n\nProperty: ${t.property_name}\nTask: ${t.task_no}\n\nOpen Northlight for the latest status.`)}catch{}}
export async function onRequestPost({request,env,params}){const a=await requireSession(request,env);if(a.error)return a.error;try{let t=await task(env,params.id);if(!t||t.deleted_at)return error(404,'Task not found.');if(t.archived_at)return error(409,'Archived tasks are read-only. Restore this task before changing its workflow.');const b=await request.json(),action=String(b.action||''),patch={},detail={};let message='';
if(action==='confirm'){if(!owns(t,a.session,'photographer'))return error(403,'Only the assigned Photographer or management can confirm this booking.');if(!['assigned','reschedule_requested'].includes(t.status))return error(409,'This booking is not awaiting confirmation.');patch.status='confirmed';patch.next_action='The shoot is booked. Northlight is waiting for capture.';message='Photographer confirmed the booking.'}
else if(action==='decline'){if(!owns(t,a.session,'photographer'))return error(403,'Only the assigned Photographer or management can decline this booking.');if(!['assigned','confirmed','reschedule_requested'].includes(t.status))return error(409,'This booking can no longer be declined.');patch.status='declined';patch.next_action='Management needs to assign another Photographer.';message='Photographer declined the booking.'}
else if(action==='source_ready'){if(!owns(t,a.session,'photographer'))return error(403,'Only the assigned Photographer or management can complete capture.');if(!['confirmed','shoot_complete','assigned'].includes(t.status))return error(409,'Source media cannot be handed to editing from the current status.');const raw=await files(env,t.id,'01_RAW'),missing=missingCoverage(raw,t.service_codes||[]);if(missing.length)return error(409,`Source media is still needed for: ${names(missing)}.`);const editorId=t.editor_user_id||await bestEditor(env,t.service_codes||[]);patch.status='raw_received';patch.editor_user_id=editorId;patch.next_action=editorId?'Editor needs to begin post-production.':'Management needs to assign an Editor.';detail.editor_user_id=editorId;message=editorId?'Source media is complete and an active Editor was routed automatically.':'Source media is complete; Editor assignment is required.'}
else if(action==='start_editing'){if(!owns(t,a.session,'editor'))return error(403,'Only the assigned Editor or management can start editing.');if(!['raw_received','revision'].includes(t.status))return error(409,'This task is not ready for editing.');patch.status='editing';patch.next_action='Editing is in progress.';message=t.status==='revision'?'Revision work started.':'Post-production started.'}
else if(action==='submit_review'){if(!owns(t,a.session,'editor'))return error(403,'Only the assigned Editor or management can submit work for review.');if(t.status!=='editing')return error(409,'Editing must be in progress before review.');const edited=await files(env,t.id,'02_EDITED'),missing=missingCoverage(edited,t.service_codes||[]);if(missing.length)return error(409,`Edited media is still needed for: ${names(missing)}.`);let published;try{published=await publishReview(env,t,edited)}catch(e){if(e.message==='no_edited_media')return error(409,'Upload edited media before submitting for review.');if(e.message==='dropbox_not_connected')return error(409,'Dropbox must be connected before review media can be published.');throw e}patch.status='review';patch.next_action='Agent needs to review the client-facing media.';detail.published_files=published;message=`${published} edited file${published===1?' was':'s were'} published for Agent review.`}
else if(action==='request_revision'){if(!owns(t,a.session,'agent'))return error(403,'Only the property Agent or management can request a revision.');if(t.status!=='review')return error(409,'This task is not currently awaiting review.');const instructions=String(b.instructions||'').trim();if(instructions.length<5)return error(400,'Revision instructions are required.');if(instructions.length>4000)return error(400,'Keep revision instructions under 4,000 characters.');let revision;try{revision=await supa(env,'rpc/northlight_request_revision',{method:'POST',payload:{p_task_id:t.id,p_requested_by:a.session.userId,p_note:instructions}})}catch(e){const m=String(e.message||'');if(m.includes('task_not_in_review'))return error(409,'This task is no longer awaiting review. Refresh the property and try again.');if(m.includes('task_archived'))return error(409,'Archived tasks are read-only.');if(m.includes('revision_note_required')||m.includes('revision_note_too_long'))return error(400,'Enter clear revision instructions under 4,000 characters.');throw e}t=await task(env,t.id);message='A revision was requested.';await notify(env,t,message);return json({ok:true,task:visibleTask(t,a.session),message,revisionNumber:Number(revision?.revision_number||t.revision_count||0)})}
else if(action==='approve_delivery'){if(!owns(t,a.session,'agent'))return error(403,'Only the property Agent or management can approve delivery.');if(t.status!=='review')return error(409,'This task is not currently awaiting final review.');const final=await files(env,t.id,'03_FINAL'),missing=missingCoverage(final,t.service_codes||[]);if(missing.length)return error(409,`Final media is still missing for: ${names(missing)}.`);patch.status='delivered';patch.next_action='No further action is required.';message='Final media was approved and delivered.'}
else return error(400,'Unknown workflow action.');
patch.metadata={...(t.metadata||{}),last_status_action:action,last_status_by:a.session.userId,last_status_at:new Date().toISOString()};await supa(env,'tasks',{method:'PATCH',query:`id=eq.${encodeURIComponent(t.id)}`,payload:patch,prefer:'return=minimal'});await logEvent(env,{task_id:t.id,type:`status_${action}`,actor_user_id:a.session.userId,message,detail});t=await task(env,t.id);await notify(env,t,message);return json({ok:true,task:visibleTask(t,a.session),message})}catch{return error(500,'Could not update task status.')}}
