import{requireSession,error,json,supa,logEvent,issueEmail,dropboxRequest,integration}from'../../../_lib/core.js';
import{syncDropbox}from'../../../_lib/dropbox-sync.js';

const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function task(env,id){return(await supa(env,'tasks',{query:`select=*&id=eq.${encodeURIComponent(id)}&limit=1`}))?.[0]||null}
function owns(t,s,role){if(['admin','owner'].includes(s.role))return true;if(role==='agent')return s.role==='agent'&&t.agent_user_id===s.userId;if(role==='photographer')return s.role==='photographer'&&t.photographer_user_id===s.userId;if(role==='editor')return s.role==='editor'&&t.editor_user_id===s.userId;return false}
async function bestEditor(env,services=[]){const rows=await supa(env,'editor_profiles',{query:'select=user_id,skills,current_load'});if(!rows.length)return null;return rows.map(x=>({...x,score:(x.skills||[]).filter(s=>services.includes(s)).length})).sort((a,b)=>b.score-a.score||Number(a.current_load||0)-Number(b.current_load||0))[0]?.user_id||null}
async function files(env,taskId,stage){return supa(env,'task_files',{query:`select=id,path,name,service_code,revision&task_id=eq.${taskId}&stage=eq.${stage}&file_type=eq.file&is_deleted=eq.false&order=modified_at.desc`})}
async function publishReview(env,t){const edited=await files(env,t.id,'02_EDITED');if(!edited.length)throw new Error('no_edited_media');const db=await integration(env,'dropbox');if(!db||db.status!=='connected')throw new Error('dropbox_not_connected');const entries=edited.map(f=>({from_path:f.path,to_path:String(f.path).replace('/02_EDITED/','/03_FINAL/')}));let d=await dropboxRequest(env,'files/copy_batch_v2',{entries,autorename:true});if(d?.['.tag']==='async_job_id'&&d.async_job_id){for(let i=0;i<12;i++){await wait(300+120*i);d=await dropboxRequest(env,'files/copy_batch/check_v2',{async_job_id:d.async_job_id});if(d?.['.tag']!=='in_progress')break}}await syncDropbox(env);return entries.length}
async function notify(env,t,message){try{await issueEmail(env,`${t.task_no} · ${message}`,`${message}\n\nProperty: ${t.property_name}\nTask: ${t.task_no}\n\nOpen Northlight for the latest status.`)}catch{}}
export async function onRequestPost({request,env,params}){const a=await requireSession(request,env);if(a.error)return a.error;try{let t=await task(env,params.id);if(!t)return error(404,'Task not found.');const b=await request.json(),action=String(b.action||''),patch={},detail={};let message='';
if(action==='confirm'){if(!owns(t,a.session,'photographer'))return error(403,'Only the assigned photographer or management can confirm this booking.');if(!['assigned','reschedule_requested'].includes(t.status))return error(409,'This booking is not awaiting confirmation.');patch.status='confirmed';patch.next_action='The shoot is booked. Northlight is waiting for capture.';message='Photographer confirmed the booking.'}
else if(action==='decline'){if(!owns(t,a.session,'photographer'))return error(403,'Only the assigned photographer or management can decline this booking.');if(!['assigned','confirmed','reschedule_requested'].includes(t.status))return error(409,'This booking can no longer be declined.');patch.status='declined';patch.next_action='Management needs to assign another photographer.';message='Photographer declined the booking.'}
else if(action==='source_ready'){if(!owns(t,a.session,'photographer'))return error(403,'Only the assigned photographer or management can complete capture.');if(!['confirmed','shoot_complete','assigned'].includes(t.status))return error(409,'Source media cannot be handed to editing from the current status.');if(!(await files(env,t.id,'01_RAW')).length)return error(409,'Upload at least one RAW/source file before handing the task to editing.');const editorId=t.editor_user_id||await bestEditor(env,t.service_codes||[]);patch.status='raw_received';patch.editor_user_id=editorId;patch.next_action=editorId?'Editor needs to begin post-production.':'Management needs to assign an editor.';detail.editor_user_id=editorId;message=editorId?'Source media is ready and an editor was routed automatically.':'Source media is ready; editor assignment is required.'}
else if(action==='start_editing'){if(!owns(t,a.session,'editor'))return error(403,'Only the assigned editor or management can start editing.');if(!['raw_received','revision'].includes(t.status))return error(409,'This task is not ready for editing.');patch.status='editing';patch.next_action='Editing is in progress.';message=t.status==='revision'?'Revision work started.':'Post-production started.'}
else if(action==='submit_review'){if(!owns(t,a.session,'editor'))return error(403,'Only the assigned editor or management can submit work for review.');if(t.status!=='editing')return error(409,'Editing must be in progress before review.');let published;try{published=await publishReview(env,t)}catch(e){if(e.message==='no_edited_media')return error(409,'Upload edited media before submitting for review.');throw e}patch.status='review';patch.next_action='Agent needs to review the client-facing media.';detail.published_files=published;message=`${published} edited file${published===1?' was':'s were'} published for Agent review.`}
else if(action==='request_revision'){if(!owns(t,a.session,'agent'))return error(403,'Only the property Agent or management can request a revision.');if(t.status!=='review')return error(409,'This task is not currently awaiting review.');patch.status='revision';patch.revision_count=Number(t.revision_count||0)+1;patch.next_action='Editor needs to complete the requested revision.';message='A revision was requested.'}
else if(action==='approve_delivery'){if(!owns(t,a.session,'agent'))return error(403,'Only the property Agent or management can approve delivery.');if(t.status!=='review')return error(409,'This task is not currently awaiting final review.');if(!(await files(env,t.id,'03_FINAL')).length)return error(409,'No review-ready final media is available yet.');patch.status='delivered';patch.next_action='No further action is required.';message='Final media was approved and delivered.'}
else return error(400,'Unknown workflow action.');
patch.metadata={...(t.metadata||{}),last_status_action:action,last_status_by:a.session.userId,last_status_at:new Date().toISOString()};await supa(env,'tasks',{method:'PATCH',query:`id=eq.${t.id}`,payload:patch,prefer:'return=minimal'});await logEvent(env,{task_id:t.id,type:`status_${action}`,actor_user_id:a.session.userId,message,detail});t=await task(env,t.id);await notify(env,t,message);return json({ok:true,task:t,message})}catch(e){return error(500,'Could not update task status.',e.message)}}
